// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: backend_repo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCheckpointByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId  string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckpointByIdRequest) Reset() {
	*x = GetCheckpointByIdRequest{}
	mi := &file_backend_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckpointByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckpointByIdRequest) ProtoMessage() {}

func (x *GetCheckpointByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckpointByIdRequest.ProtoReflect.Descriptor instead.
func (*GetCheckpointByIdRequest) Descriptor() ([]byte, []int) {
	return file_backend_repo_proto_rawDescGZIP(), []int{0}
}

func (x *GetCheckpointByIdRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

type GetCheckpointByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Checkpoint    *Checkpoint            `protobuf:"bytes,2,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckpointByIdResponse) Reset() {
	*x = GetCheckpointByIdResponse{}
	mi := &file_backend_repo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckpointByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckpointByIdResponse) ProtoMessage() {}

func (x *GetCheckpointByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_repo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckpointByIdResponse.ProtoReflect.Descriptor instead.
func (*GetCheckpointByIdResponse) Descriptor() ([]byte, []int) {
	return file_backend_repo_proto_rawDescGZIP(), []int{1}
}

func (x *GetCheckpointByIdResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetCheckpointByIdResponse) GetCheckpoint() *Checkpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *GetCheckpointByIdResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GetLatestCheckpointByStubIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StubId        string                 `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestCheckpointByStubIdRequest) Reset() {
	*x = GetLatestCheckpointByStubIdRequest{}
	mi := &file_backend_repo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestCheckpointByStubIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestCheckpointByStubIdRequest) ProtoMessage() {}

func (x *GetLatestCheckpointByStubIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_repo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestCheckpointByStubIdRequest.ProtoReflect.Descriptor instead.
func (*GetLatestCheckpointByStubIdRequest) Descriptor() ([]byte, []int) {
	return file_backend_repo_proto_rawDescGZIP(), []int{2}
}

func (x *GetLatestCheckpointByStubIdRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

type GetLatestCheckpointByStubIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Checkpoint    *Checkpoint            `protobuf:"bytes,2,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestCheckpointByStubIdResponse) Reset() {
	*x = GetLatestCheckpointByStubIdResponse{}
	mi := &file_backend_repo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestCheckpointByStubIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestCheckpointByStubIdResponse) ProtoMessage() {}

func (x *GetLatestCheckpointByStubIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_repo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestCheckpointByStubIdResponse.ProtoReflect.Descriptor instead.
func (*GetLatestCheckpointByStubIdResponse) Descriptor() ([]byte, []int) {
	return file_backend_repo_proto_rawDescGZIP(), []int{3}
}

func (x *GetLatestCheckpointByStubIdResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetLatestCheckpointByStubIdResponse) GetCheckpoint() *Checkpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *GetLatestCheckpointByStubIdResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ListCheckpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCheckpointsRequest) Reset() {
	*x = ListCheckpointsRequest{}
	mi := &file_backend_repo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCheckpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCheckpointsRequest) ProtoMessage() {}

func (x *ListCheckpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_repo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCheckpointsRequest.ProtoReflect.Descriptor instead.
func (*ListCheckpointsRequest) Descriptor() ([]byte, []int) {
	return file_backend_repo_proto_rawDescGZIP(), []int{4}
}

func (x *ListCheckpointsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type ListCheckpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Checkpoints   []*Checkpoint          `protobuf:"bytes,2,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCheckpointsResponse) Reset() {
	*x = ListCheckpointsResponse{}
	mi := &file_backend_repo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCheckpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCheckpointsResponse) ProtoMessage() {}

func (x *ListCheckpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_repo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCheckpointsResponse.ProtoReflect.Descriptor instead.
func (*ListCheckpointsResponse) Descriptor() ([]byte, []int) {
	return file_backend_repo_proto_rawDescGZIP(), []int{5}
}

func (x *ListCheckpointsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ListCheckpointsResponse) GetCheckpoints() []*Checkpoint {
	if x != nil {
		return x.Checkpoints
	}
	return nil
}

func (x *ListCheckpointsResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type CreateCheckpointRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId      string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	SourceContainerId string                 `protobuf:"bytes,2,opt,name=source_container_id,json=sourceContainerId,proto3" json:"source_container_id,omitempty"`
	ContainerIp       string                 `protobuf:"bytes,3,opt,name=container_ip,json=containerIp,proto3" json:"container_ip,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	RemoteKey         string                 `protobuf:"bytes,5,opt,name=remote_key,json=remoteKey,proto3" json:"remote_key,omitempty"`
	StubId            string                 `protobuf:"bytes,6,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	ExposedPorts      []uint32               `protobuf:"varint,7,rep,packed,name=exposed_ports,json=exposedPorts,proto3" json:"exposed_ports,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateCheckpointRequest) Reset() {
	*x = CreateCheckpointRequest{}
	mi := &file_backend_repo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckpointRequest) ProtoMessage() {}

func (x *CreateCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_repo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckpointRequest.ProtoReflect.Descriptor instead.
func (*CreateCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_backend_repo_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCheckpointRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *CreateCheckpointRequest) GetSourceContainerId() string {
	if x != nil {
		return x.SourceContainerId
	}
	return ""
}

func (x *CreateCheckpointRequest) GetContainerIp() string {
	if x != nil {
		return x.ContainerIp
	}
	return ""
}

func (x *CreateCheckpointRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateCheckpointRequest) GetRemoteKey() string {
	if x != nil {
		return x.RemoteKey
	}
	return ""
}

func (x *CreateCheckpointRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *CreateCheckpointRequest) GetExposedPorts() []uint32 {
	if x != nil {
		return x.ExposedPorts
	}
	return nil
}

type CreateCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Checkpoint    *Checkpoint            `protobuf:"bytes,2,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCheckpointResponse) Reset() {
	*x = CreateCheckpointResponse{}
	mi := &file_backend_repo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckpointResponse) ProtoMessage() {}

func (x *CreateCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_repo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckpointResponse.ProtoReflect.Descriptor instead.
func (*CreateCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_backend_repo_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCheckpointResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CreateCheckpointResponse) GetCheckpoint() *Checkpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *CreateCheckpointResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type UpdateCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId  string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCheckpointRequest) Reset() {
	*x = UpdateCheckpointRequest{}
	mi := &file_backend_repo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCheckpointRequest) ProtoMessage() {}

func (x *UpdateCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_repo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCheckpointRequest.ProtoReflect.Descriptor instead.
func (*UpdateCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_backend_repo_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCheckpointRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *UpdateCheckpointRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Checkpoint    *Checkpoint            `protobuf:"bytes,2,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCheckpointResponse) Reset() {
	*x = UpdateCheckpointResponse{}
	mi := &file_backend_repo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCheckpointResponse) ProtoMessage() {}

func (x *UpdateCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_repo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCheckpointResponse.ProtoReflect.Descriptor instead.
func (*UpdateCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_backend_repo_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCheckpointResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UpdateCheckpointResponse) GetCheckpoint() *Checkpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *UpdateCheckpointResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_backend_repo_proto protoreflect.FileDescriptor

const file_backend_repo_proto_rawDesc = "" +
	"\n" +
	"\x12backend_repo.proto\x1a\vtypes.proto\"?\n" +
	"\x18GetCheckpointByIdRequest\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\"{\n" +
	"\x19GetCheckpointByIdResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x121\n" +
	"\n" +
	"checkpoint\x18\x02 \x01(\v2\x11.types.CheckpointR\n" +
	"checkpoint\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\"=\n" +
	"\"GetLatestCheckpointByStubIdRequest\x12\x17\n" +
	"\astub_id\x18\x01 \x01(\tR\x06stubId\"\x85\x01\n" +
	"#GetLatestCheckpointByStubIdResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x121\n" +
	"\n" +
	"checkpoint\x18\x02 \x01(\v2\x11.types.CheckpointR\n" +
	"checkpoint\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\";\n" +
	"\x16ListCheckpointsRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"{\n" +
	"\x17ListCheckpointsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x123\n" +
	"\vcheckpoints\x18\x02 \x03(\v2\x11.types.CheckpointR\vcheckpoints\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\"\x86\x02\n" +
	"\x17CreateCheckpointRequest\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12.\n" +
	"\x13source_container_id\x18\x02 \x01(\tR\x11sourceContainerId\x12!\n" +
	"\fcontainer_ip\x18\x03 \x01(\tR\vcontainerIp\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"remote_key\x18\x05 \x01(\tR\tremoteKey\x12\x17\n" +
	"\astub_id\x18\x06 \x01(\tR\x06stubId\x12#\n" +
	"\rexposed_ports\x18\a \x03(\rR\fexposedPorts\"z\n" +
	"\x18CreateCheckpointResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x121\n" +
	"\n" +
	"checkpoint\x18\x02 \x01(\v2\x11.types.CheckpointR\n" +
	"checkpoint\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\"V\n" +
	"\x17UpdateCheckpointRequest\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"z\n" +
	"\x18UpdateCheckpointResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x121\n" +
	"\n" +
	"checkpoint\x18\x02 \x01(\v2\x11.types.CheckpointR\n" +
	"checkpoint\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg2\xa8\x03\n" +
	"\x18BackendRepositoryService\x12J\n" +
	"\x11GetCheckpointById\x12\x19.GetCheckpointByIdRequest\x1a\x1a.GetCheckpointByIdResponse\x12h\n" +
	"\x1bGetLatestCheckpointByStubId\x12#.GetLatestCheckpointByStubIdRequest\x1a$.GetLatestCheckpointByStubIdResponse\x12D\n" +
	"\x0fListCheckpoints\x12\x17.ListCheckpointsRequest\x1a\x18.ListCheckpointsResponse\x12G\n" +
	"\x10CreateCheckpoint\x12\x18.CreateCheckpointRequest\x1a\x19.CreateCheckpointResponse\x12G\n" +
	"\x10UpdateCheckpoint\x12\x18.UpdateCheckpointRequest\x1a\x19.UpdateCheckpointResponseB#Z!github.com/beam-cloud/beta9/protob\x06proto3"

var (
	file_backend_repo_proto_rawDescOnce sync.Once
	file_backend_repo_proto_rawDescData []byte
)

func file_backend_repo_proto_rawDescGZIP() []byte {
	file_backend_repo_proto_rawDescOnce.Do(func() {
		file_backend_repo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_repo_proto_rawDesc), len(file_backend_repo_proto_rawDesc)))
	})
	return file_backend_repo_proto_rawDescData
}

var file_backend_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_backend_repo_proto_goTypes = []any{
	(*GetCheckpointByIdRequest)(nil),            // 0: GetCheckpointByIdRequest
	(*GetCheckpointByIdResponse)(nil),           // 1: GetCheckpointByIdResponse
	(*GetLatestCheckpointByStubIdRequest)(nil),  // 2: GetLatestCheckpointByStubIdRequest
	(*GetLatestCheckpointByStubIdResponse)(nil), // 3: GetLatestCheckpointByStubIdResponse
	(*ListCheckpointsRequest)(nil),              // 4: ListCheckpointsRequest
	(*ListCheckpointsResponse)(nil),             // 5: ListCheckpointsResponse
	(*CreateCheckpointRequest)(nil),             // 6: CreateCheckpointRequest
	(*CreateCheckpointResponse)(nil),            // 7: CreateCheckpointResponse
	(*UpdateCheckpointRequest)(nil),             // 8: UpdateCheckpointRequest
	(*UpdateCheckpointResponse)(nil),            // 9: UpdateCheckpointResponse
	(*Checkpoint)(nil),                          // 10: types.Checkpoint
}
var file_backend_repo_proto_depIdxs = []int32{
	10, // 0: GetCheckpointByIdResponse.checkpoint:type_name -> types.Checkpoint
	10, // 1: GetLatestCheckpointByStubIdResponse.checkpoint:type_name -> types.Checkpoint
	10, // 2: ListCheckpointsResponse.checkpoints:type_name -> types.Checkpoint
	10, // 3: CreateCheckpointResponse.checkpoint:type_name -> types.Checkpoint
	10, // 4: UpdateCheckpointResponse.checkpoint:type_name -> types.Checkpoint
	0,  // 5: BackendRepositoryService.GetCheckpointById:input_type -> GetCheckpointByIdRequest
	2,  // 6: BackendRepositoryService.GetLatestCheckpointByStubId:input_type -> GetLatestCheckpointByStubIdRequest
	4,  // 7: BackendRepositoryService.ListCheckpoints:input_type -> ListCheckpointsRequest
	6,  // 8: BackendRepositoryService.CreateCheckpoint:input_type -> CreateCheckpointRequest
	8,  // 9: BackendRepositoryService.UpdateCheckpoint:input_type -> UpdateCheckpointRequest
	1,  // 10: BackendRepositoryService.GetCheckpointById:output_type -> GetCheckpointByIdResponse
	3,  // 11: BackendRepositoryService.GetLatestCheckpointByStubId:output_type -> GetLatestCheckpointByStubIdResponse
	5,  // 12: BackendRepositoryService.ListCheckpoints:output_type -> ListCheckpointsResponse
	7,  // 13: BackendRepositoryService.CreateCheckpoint:output_type -> CreateCheckpointResponse
	9,  // 14: BackendRepositoryService.UpdateCheckpoint:output_type -> UpdateCheckpointResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_backend_repo_proto_init() }
func file_backend_repo_proto_init() {
	if File_backend_repo_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_repo_proto_rawDesc), len(file_backend_repo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_repo_proto_goTypes,
		DependencyIndexes: file_backend_repo_proto_depIdxs,
		MessageInfos:      file_backend_repo_proto_msgTypes,
	}.Build()
	File_backend_repo_proto = out.File
	file_backend_repo_proto_goTypes = nil
	file_backend_repo_proto_depIdxs = nil
}
