// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: bot.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PopBotTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StubId         string                 `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TransitionName string                 `protobuf:"bytes,3,opt,name=transition_name,json=transitionName,proto3" json:"transition_name,omitempty"`
	TaskId         string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PopBotTaskRequest) Reset() {
	*x = PopBotTaskRequest{}
	mi := &file_bot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopBotTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopBotTaskRequest) ProtoMessage() {}

func (x *PopBotTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopBotTaskRequest.ProtoReflect.Descriptor instead.
func (*PopBotTaskRequest) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{0}
}

func (x *PopBotTaskRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *PopBotTaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PopBotTaskRequest) GetTransitionName() string {
	if x != nil {
		return x.TransitionName
	}
	return ""
}

func (x *PopBotTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type PopBotTaskResponse struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Ok            bool                                      `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Markers       map[string]*PopBotTaskResponse_MarkerList `protobuf:"bytes,2,rep,name=markers,proto3" json:"markers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopBotTaskResponse) Reset() {
	*x = PopBotTaskResponse{}
	mi := &file_bot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopBotTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopBotTaskResponse) ProtoMessage() {}

func (x *PopBotTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopBotTaskResponse.ProtoReflect.Descriptor instead.
func (*PopBotTaskResponse) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{1}
}

func (x *PopBotTaskResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PopBotTaskResponse) GetMarkers() map[string]*PopBotTaskResponse_MarkerList {
	if x != nil {
		return x.Markers
	}
	return nil
}

type MarkerField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldName     string                 `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	FieldValue    string                 `protobuf:"bytes,2,opt,name=field_value,json=fieldValue,proto3" json:"field_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkerField) Reset() {
	*x = MarkerField{}
	mi := &file_bot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkerField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkerField) ProtoMessage() {}

func (x *MarkerField) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkerField.ProtoReflect.Descriptor instead.
func (*MarkerField) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{2}
}

func (x *MarkerField) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *MarkerField) GetFieldValue() string {
	if x != nil {
		return x.FieldValue
	}
	return ""
}

type Marker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationName  string                 `protobuf:"bytes,1,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	Fields        []*MarkerField         `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	SourceTaskId  string                 `protobuf:"bytes,3,opt,name=source_task_id,json=sourceTaskId,proto3" json:"source_task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Marker) Reset() {
	*x = Marker{}
	mi := &file_bot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Marker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Marker) ProtoMessage() {}

func (x *Marker) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Marker.ProtoReflect.Descriptor instead.
func (*Marker) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{3}
}

func (x *Marker) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

func (x *Marker) GetFields() []*MarkerField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Marker) GetSourceTaskId() string {
	if x != nil {
		return x.SourceTaskId
	}
	return ""
}

type PushBotMarkersRequest struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	StubId        string                                       `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	SessionId     string                                       `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Markers       map[string]*PushBotMarkersRequest_MarkerList `protobuf:"bytes,3,rep,name=markers,proto3" json:"markers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SourceTaskId  string                                       `protobuf:"bytes,5,opt,name=source_task_id,json=sourceTaskId,proto3" json:"source_task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBotMarkersRequest) Reset() {
	*x = PushBotMarkersRequest{}
	mi := &file_bot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBotMarkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBotMarkersRequest) ProtoMessage() {}

func (x *PushBotMarkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBotMarkersRequest.ProtoReflect.Descriptor instead.
func (*PushBotMarkersRequest) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{4}
}

func (x *PushBotMarkersRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *PushBotMarkersRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PushBotMarkersRequest) GetMarkers() map[string]*PushBotMarkersRequest_MarkerList {
	if x != nil {
		return x.Markers
	}
	return nil
}

func (x *PushBotMarkersRequest) GetSourceTaskId() string {
	if x != nil {
		return x.SourceTaskId
	}
	return ""
}

type PushBotMarkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBotMarkersResponse) Reset() {
	*x = PushBotMarkersResponse{}
	mi := &file_bot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBotMarkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBotMarkersResponse) ProtoMessage() {}

func (x *PushBotMarkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBotMarkersResponse.ProtoReflect.Descriptor instead.
func (*PushBotMarkersResponse) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{5}
}

func (x *PushBotMarkersResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type PushBotEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StubId        string                 `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventValue    string                 `protobuf:"bytes,4,opt,name=event_value,json=eventValue,proto3" json:"event_value,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBotEventRequest) Reset() {
	*x = PushBotEventRequest{}
	mi := &file_bot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBotEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBotEventRequest) ProtoMessage() {}

func (x *PushBotEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBotEventRequest.ProtoReflect.Descriptor instead.
func (*PushBotEventRequest) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{6}
}

func (x *PushBotEventRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *PushBotEventRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PushBotEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PushBotEventRequest) GetEventValue() string {
	if x != nil {
		return x.EventValue
	}
	return ""
}

func (x *PushBotEventRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PushBotEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBotEventResponse) Reset() {
	*x = PushBotEventResponse{}
	mi := &file_bot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBotEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBotEventResponse) ProtoMessage() {}

func (x *PushBotEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBotEventResponse.ProtoReflect.Descriptor instead.
func (*PushBotEventResponse) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{7}
}

func (x *PushBotEventResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PushBotEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type PushBotEventBlockingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StubId         string                 `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventType      string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventValue     string                 `protobuf:"bytes,4,opt,name=event_value,json=eventValue,proto3" json:"event_value,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushBotEventBlockingRequest) Reset() {
	*x = PushBotEventBlockingRequest{}
	mi := &file_bot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBotEventBlockingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBotEventBlockingRequest) ProtoMessage() {}

func (x *PushBotEventBlockingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBotEventBlockingRequest.ProtoReflect.Descriptor instead.
func (*PushBotEventBlockingRequest) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{8}
}

func (x *PushBotEventBlockingRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *PushBotEventBlockingRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PushBotEventBlockingRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PushBotEventBlockingRequest) GetEventValue() string {
	if x != nil {
		return x.EventValue
	}
	return ""
}

func (x *PushBotEventBlockingRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PushBotEventBlockingRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type PushBotEventBlockingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Event         *BotEvent              `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBotEventBlockingResponse) Reset() {
	*x = PushBotEventBlockingResponse{}
	mi := &file_bot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBotEventBlockingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBotEventBlockingResponse) ProtoMessage() {}

func (x *PushBotEventBlockingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBotEventBlockingResponse.ProtoReflect.Descriptor instead.
func (*PushBotEventBlockingResponse) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{9}
}

func (x *PushBotEventBlockingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PushBotEventBlockingResponse) GetEvent() *BotEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type BotEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotEvent) Reset() {
	*x = BotEvent{}
	mi := &file_bot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotEvent) ProtoMessage() {}

func (x *BotEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotEvent.ProtoReflect.Descriptor instead.
func (*BotEvent) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{10}
}

func (x *BotEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BotEvent) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *BotEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PopBotTaskResponse_MarkerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markers       []*Marker              `protobuf:"bytes,1,rep,name=markers,proto3" json:"markers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopBotTaskResponse_MarkerList) Reset() {
	*x = PopBotTaskResponse_MarkerList{}
	mi := &file_bot_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopBotTaskResponse_MarkerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopBotTaskResponse_MarkerList) ProtoMessage() {}

func (x *PopBotTaskResponse_MarkerList) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopBotTaskResponse_MarkerList.ProtoReflect.Descriptor instead.
func (*PopBotTaskResponse_MarkerList) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{1, 1}
}

func (x *PopBotTaskResponse_MarkerList) GetMarkers() []*Marker {
	if x != nil {
		return x.Markers
	}
	return nil
}

type PushBotMarkersRequest_MarkerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markers       []*Marker              `protobuf:"bytes,4,rep,name=markers,proto3" json:"markers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBotMarkersRequest_MarkerList) Reset() {
	*x = PushBotMarkersRequest_MarkerList{}
	mi := &file_bot_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBotMarkersRequest_MarkerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBotMarkersRequest_MarkerList) ProtoMessage() {}

func (x *PushBotMarkersRequest_MarkerList) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBotMarkersRequest_MarkerList.ProtoReflect.Descriptor instead.
func (*PushBotMarkersRequest_MarkerList) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{4, 1}
}

func (x *PushBotMarkersRequest_MarkerList) GetMarkers() []*Marker {
	if x != nil {
		return x.Markers
	}
	return nil
}

var File_bot_proto protoreflect.FileDescriptor

const file_bot_proto_rawDesc = "" +
	"\n" +
	"\tbot.proto\x12\x03bot\"\x8d\x01\n" +
	"\x11PopBotTaskRequest\x12\x17\n" +
	"\astub_id\x18\x01 \x01(\tR\x06stubId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12'\n" +
	"\x0ftransition_name\x18\x03 \x01(\tR\x0etransitionName\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\"\xf9\x01\n" +
	"\x12PopBotTaskResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12>\n" +
	"\amarkers\x18\x02 \x03(\v2$.bot.PopBotTaskResponse.MarkersEntryR\amarkers\x1a^\n" +
	"\fMarkersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".bot.PopBotTaskResponse.MarkerListR\x05value:\x028\x01\x1a3\n" +
	"\n" +
	"MarkerList\x12%\n" +
	"\amarkers\x18\x01 \x03(\v2\v.bot.MarkerR\amarkers\"M\n" +
	"\vMarkerField\x12\x1d\n" +
	"\n" +
	"field_name\x18\x01 \x01(\tR\tfieldName\x12\x1f\n" +
	"\vfield_value\x18\x02 \x01(\tR\n" +
	"fieldValue\"}\n" +
	"\x06Marker\x12#\n" +
	"\rlocation_name\x18\x01 \x01(\tR\flocationName\x12(\n" +
	"\x06fields\x18\x02 \x03(\v2\x10.bot.MarkerFieldR\x06fields\x12$\n" +
	"\x0esource_task_id\x18\x03 \x01(\tR\fsourceTaskId\"\xd0\x02\n" +
	"\x15PushBotMarkersRequest\x12\x17\n" +
	"\astub_id\x18\x01 \x01(\tR\x06stubId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12A\n" +
	"\amarkers\x18\x03 \x03(\v2'.bot.PushBotMarkersRequest.MarkersEntryR\amarkers\x12$\n" +
	"\x0esource_task_id\x18\x05 \x01(\tR\fsourceTaskId\x1aa\n" +
	"\fMarkersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.bot.PushBotMarkersRequest.MarkerListR\x05value:\x028\x01\x1a3\n" +
	"\n" +
	"MarkerList\x12%\n" +
	"\amarkers\x18\x04 \x03(\v2\v.bot.MarkerR\amarkers\"(\n" +
	"\x16PushBotMarkersResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x8e\x02\n" +
	"\x13PushBotEventRequest\x12\x17\n" +
	"\astub_id\x18\x01 \x01(\tR\x06stubId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1f\n" +
	"\vevent_value\x18\x04 \x01(\tR\n" +
	"eventValue\x12B\n" +
	"\bmetadata\x18\x05 \x03(\v2&.bot.PushBotEventRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x14PushBotEventResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\"\xc7\x02\n" +
	"\x1bPushBotEventBlockingRequest\x12\x17\n" +
	"\astub_id\x18\x01 \x01(\tR\x06stubId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1f\n" +
	"\vevent_value\x18\x04 \x01(\tR\n" +
	"eventValue\x12J\n" +
	"\bmetadata\x18\x05 \x03(\v2..bot.PushBotEventBlockingRequest.MetadataEntryR\bmetadata\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x1cPushBotEventBlockingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12#\n" +
	"\x05event\x18\x02 \x01(\v2\r.bot.BotEventR\x05event\"\xaa\x01\n" +
	"\bBotEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x127\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1b.bot.BotEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc0\x02\n" +
	"\n" +
	"BotService\x12?\n" +
	"\n" +
	"PopBotTask\x12\x16.bot.PopBotTaskRequest\x1a\x17.bot.PopBotTaskResponse\"\x00\x12K\n" +
	"\x0ePushBotMarkers\x12\x1a.bot.PushBotMarkersRequest\x1a\x1b.bot.PushBotMarkersResponse\"\x00\x12E\n" +
	"\fPushBotEvent\x12\x18.bot.PushBotEventRequest\x1a\x19.bot.PushBotEventResponse\"\x00\x12]\n" +
	"\x14PushBotEventBlocking\x12 .bot.PushBotEventBlockingRequest\x1a!.bot.PushBotEventBlockingResponse\"\x00B#Z!github.com/beam-cloud/beta9/protob\x06proto3"

var (
	file_bot_proto_rawDescOnce sync.Once
	file_bot_proto_rawDescData []byte
)

func file_bot_proto_rawDescGZIP() []byte {
	file_bot_proto_rawDescOnce.Do(func() {
		file_bot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bot_proto_rawDesc), len(file_bot_proto_rawDesc)))
	})
	return file_bot_proto_rawDescData
}

var file_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_bot_proto_goTypes = []any{
	(*PopBotTaskRequest)(nil),                // 0: bot.PopBotTaskRequest
	(*PopBotTaskResponse)(nil),               // 1: bot.PopBotTaskResponse
	(*MarkerField)(nil),                      // 2: bot.MarkerField
	(*Marker)(nil),                           // 3: bot.Marker
	(*PushBotMarkersRequest)(nil),            // 4: bot.PushBotMarkersRequest
	(*PushBotMarkersResponse)(nil),           // 5: bot.PushBotMarkersResponse
	(*PushBotEventRequest)(nil),              // 6: bot.PushBotEventRequest
	(*PushBotEventResponse)(nil),             // 7: bot.PushBotEventResponse
	(*PushBotEventBlockingRequest)(nil),      // 8: bot.PushBotEventBlockingRequest
	(*PushBotEventBlockingResponse)(nil),     // 9: bot.PushBotEventBlockingResponse
	(*BotEvent)(nil),                         // 10: bot.BotEvent
	nil,                                      // 11: bot.PopBotTaskResponse.MarkersEntry
	(*PopBotTaskResponse_MarkerList)(nil),    // 12: bot.PopBotTaskResponse.MarkerList
	nil,                                      // 13: bot.PushBotMarkersRequest.MarkersEntry
	(*PushBotMarkersRequest_MarkerList)(nil), // 14: bot.PushBotMarkersRequest.MarkerList
	nil,                                      // 15: bot.PushBotEventRequest.MetadataEntry
	nil,                                      // 16: bot.PushBotEventBlockingRequest.MetadataEntry
	nil,                                      // 17: bot.BotEvent.MetadataEntry
}
var file_bot_proto_depIdxs = []int32{
	11, // 0: bot.PopBotTaskResponse.markers:type_name -> bot.PopBotTaskResponse.MarkersEntry
	2,  // 1: bot.Marker.fields:type_name -> bot.MarkerField
	13, // 2: bot.PushBotMarkersRequest.markers:type_name -> bot.PushBotMarkersRequest.MarkersEntry
	15, // 3: bot.PushBotEventRequest.metadata:type_name -> bot.PushBotEventRequest.MetadataEntry
	16, // 4: bot.PushBotEventBlockingRequest.metadata:type_name -> bot.PushBotEventBlockingRequest.MetadataEntry
	10, // 5: bot.PushBotEventBlockingResponse.event:type_name -> bot.BotEvent
	17, // 6: bot.BotEvent.metadata:type_name -> bot.BotEvent.MetadataEntry
	12, // 7: bot.PopBotTaskResponse.MarkersEntry.value:type_name -> bot.PopBotTaskResponse.MarkerList
	3,  // 8: bot.PopBotTaskResponse.MarkerList.markers:type_name -> bot.Marker
	14, // 9: bot.PushBotMarkersRequest.MarkersEntry.value:type_name -> bot.PushBotMarkersRequest.MarkerList
	3,  // 10: bot.PushBotMarkersRequest.MarkerList.markers:type_name -> bot.Marker
	0,  // 11: bot.BotService.PopBotTask:input_type -> bot.PopBotTaskRequest
	4,  // 12: bot.BotService.PushBotMarkers:input_type -> bot.PushBotMarkersRequest
	6,  // 13: bot.BotService.PushBotEvent:input_type -> bot.PushBotEventRequest
	8,  // 14: bot.BotService.PushBotEventBlocking:input_type -> bot.PushBotEventBlockingRequest
	1,  // 15: bot.BotService.PopBotTask:output_type -> bot.PopBotTaskResponse
	5,  // 16: bot.BotService.PushBotMarkers:output_type -> bot.PushBotMarkersResponse
	7,  // 17: bot.BotService.PushBotEvent:output_type -> bot.PushBotEventResponse
	9,  // 18: bot.BotService.PushBotEventBlocking:output_type -> bot.PushBotEventBlockingResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_bot_proto_init() }
func file_bot_proto_init() {
	if File_bot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bot_proto_rawDesc), len(file_bot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bot_proto_goTypes,
		DependencyIndexes: file_bot_proto_depIdxs,
		MessageInfos:      file_bot_proto_msgTypes,
	}.Build()
	File_bot_proto = out.File
	file_bot_proto_goTypes = nil
	file_bot_proto_depIdxs = nil
}
