// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: endpoint.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartEndpointServeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StubId        string                 `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartEndpointServeRequest) Reset() {
	*x = StartEndpointServeRequest{}
	mi := &file_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartEndpointServeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEndpointServeRequest) ProtoMessage() {}

func (x *StartEndpointServeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEndpointServeRequest.ProtoReflect.Descriptor instead.
func (*StartEndpointServeRequest) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *StartEndpointServeRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *StartEndpointServeRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type StartEndpointServeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartEndpointServeResponse) Reset() {
	*x = StartEndpointServeResponse{}
	mi := &file_endpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartEndpointServeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEndpointServeResponse) ProtoMessage() {}

func (x *StartEndpointServeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEndpointServeResponse.ProtoReflect.Descriptor instead.
func (*StartEndpointServeResponse) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *StartEndpointServeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StartEndpointServeResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StartEndpointServeResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_endpoint_proto protoreflect.FileDescriptor

const file_endpoint_proto_rawDesc = "" +
	"\n" +
	"\x0eendpoint.proto\x12\bendpoint\"N\n" +
	"\x19StartEndpointServeRequest\x12\x17\n" +
	"\astub_id\x18\x01 \x01(\tR\x06stubId\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\"l\n" +
	"\x1aStartEndpointServeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg2t\n" +
	"\x0fEndpointService\x12a\n" +
	"\x12StartEndpointServe\x12#.endpoint.StartEndpointServeRequest\x1a$.endpoint.StartEndpointServeResponse\"\x00B#Z!github.com/beam-cloud/beta9/protob\x06proto3"

var (
	file_endpoint_proto_rawDescOnce sync.Once
	file_endpoint_proto_rawDescData []byte
)

func file_endpoint_proto_rawDescGZIP() []byte {
	file_endpoint_proto_rawDescOnce.Do(func() {
		file_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoint_proto_rawDesc), len(file_endpoint_proto_rawDesc)))
	})
	return file_endpoint_proto_rawDescData
}

var file_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpoint_proto_goTypes = []any{
	(*StartEndpointServeRequest)(nil),  // 0: endpoint.StartEndpointServeRequest
	(*StartEndpointServeResponse)(nil), // 1: endpoint.StartEndpointServeResponse
}
var file_endpoint_proto_depIdxs = []int32{
	0, // 0: endpoint.EndpointService.StartEndpointServe:input_type -> endpoint.StartEndpointServeRequest
	1, // 1: endpoint.EndpointService.StartEndpointServe:output_type -> endpoint.StartEndpointServeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_endpoint_proto_init() }
func file_endpoint_proto_init() {
	if File_endpoint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoint_proto_rawDesc), len(file_endpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_endpoint_proto_goTypes,
		DependencyIndexes: file_endpoint_proto_depIdxs,
		MessageInfos:      file_endpoint_proto_msgTypes,
	}.Build()
	File_endpoint_proto = out.File
	file_endpoint_proto_goTypes = nil
	file_endpoint_proto_depIdxs = nil
}
