// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: function.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FunctionInvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StubId        string                 `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	Args          []byte                 `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	Headless      bool                   `protobuf:"varint,3,opt,name=headless,proto3" json:"headless,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionInvokeRequest) Reset() {
	*x = FunctionInvokeRequest{}
	mi := &file_function_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionInvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInvokeRequest) ProtoMessage() {}

func (x *FunctionInvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInvokeRequest.ProtoReflect.Descriptor instead.
func (*FunctionInvokeRequest) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{0}
}

func (x *FunctionInvokeRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *FunctionInvokeRequest) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *FunctionInvokeRequest) GetHeadless() bool {
	if x != nil {
		return x.Headless
	}
	return false
}

type FunctionInvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Result        []byte                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionInvokeResponse) Reset() {
	*x = FunctionInvokeResponse{}
	mi := &file_function_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionInvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInvokeResponse) ProtoMessage() {}

func (x *FunctionInvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInvokeResponse.ProtoReflect.Descriptor instead.
func (*FunctionInvokeResponse) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{1}
}

func (x *FunctionInvokeResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *FunctionInvokeResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *FunctionInvokeResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *FunctionInvokeResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *FunctionInvokeResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type FunctionGetArgsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionGetArgsRequest) Reset() {
	*x = FunctionGetArgsRequest{}
	mi := &file_function_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionGetArgsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionGetArgsRequest) ProtoMessage() {}

func (x *FunctionGetArgsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionGetArgsRequest.ProtoReflect.Descriptor instead.
func (*FunctionGetArgsRequest) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{2}
}

func (x *FunctionGetArgsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type FunctionGetArgsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Args          []byte                 `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionGetArgsResponse) Reset() {
	*x = FunctionGetArgsResponse{}
	mi := &file_function_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionGetArgsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionGetArgsResponse) ProtoMessage() {}

func (x *FunctionGetArgsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionGetArgsResponse.ProtoReflect.Descriptor instead.
func (*FunctionGetArgsResponse) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{3}
}

func (x *FunctionGetArgsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *FunctionGetArgsResponse) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

type FunctionSetResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionSetResultRequest) Reset() {
	*x = FunctionSetResultRequest{}
	mi := &file_function_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionSetResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionSetResultRequest) ProtoMessage() {}

func (x *FunctionSetResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionSetResultRequest.ProtoReflect.Descriptor instead.
func (*FunctionSetResultRequest) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{4}
}

func (x *FunctionSetResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *FunctionSetResultRequest) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type FunctionSetResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionSetResultResponse) Reset() {
	*x = FunctionSetResultResponse{}
	mi := &file_function_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionSetResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionSetResultResponse) ProtoMessage() {}

func (x *FunctionSetResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionSetResultResponse.ProtoReflect.Descriptor instead.
func (*FunctionSetResultResponse) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{5}
}

func (x *FunctionSetResultResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type FunctionMonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StubId        string                 `protobuf:"bytes,2,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionMonitorRequest) Reset() {
	*x = FunctionMonitorRequest{}
	mi := &file_function_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionMonitorRequest) ProtoMessage() {}

func (x *FunctionMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionMonitorRequest.ProtoReflect.Descriptor instead.
func (*FunctionMonitorRequest) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{6}
}

func (x *FunctionMonitorRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *FunctionMonitorRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *FunctionMonitorRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type FunctionMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Cancelled     bool                   `protobuf:"varint,2,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	Complete      bool                   `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"`
	TimedOut      bool                   `protobuf:"varint,4,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionMonitorResponse) Reset() {
	*x = FunctionMonitorResponse{}
	mi := &file_function_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionMonitorResponse) ProtoMessage() {}

func (x *FunctionMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionMonitorResponse.ProtoReflect.Descriptor instead.
func (*FunctionMonitorResponse) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{7}
}

func (x *FunctionMonitorResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *FunctionMonitorResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *FunctionMonitorResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *FunctionMonitorResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

type FunctionScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StubId        string                 `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	When          string                 `protobuf:"bytes,2,opt,name=when,proto3" json:"when,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,3,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionScheduleRequest) Reset() {
	*x = FunctionScheduleRequest{}
	mi := &file_function_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionScheduleRequest) ProtoMessage() {}

func (x *FunctionScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionScheduleRequest.ProtoReflect.Descriptor instead.
func (*FunctionScheduleRequest) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{8}
}

func (x *FunctionScheduleRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *FunctionScheduleRequest) GetWhen() string {
	if x != nil {
		return x.When
	}
	return ""
}

func (x *FunctionScheduleRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type FunctionScheduleResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ok             bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrMsg         string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	ScheduledJobId string                 `protobuf:"bytes,3,opt,name=scheduled_job_id,json=scheduledJobId,proto3" json:"scheduled_job_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FunctionScheduleResponse) Reset() {
	*x = FunctionScheduleResponse{}
	mi := &file_function_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionScheduleResponse) ProtoMessage() {}

func (x *FunctionScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionScheduleResponse.ProtoReflect.Descriptor instead.
func (*FunctionScheduleResponse) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{9}
}

func (x *FunctionScheduleResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *FunctionScheduleResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *FunctionScheduleResponse) GetScheduledJobId() string {
	if x != nil {
		return x.ScheduledJobId
	}
	return ""
}

type FunctionInvokeGangRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StubId         string                 `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	Args           []byte                 `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	Headless       bool                   `protobuf:"varint,3,opt,name=headless,proto3" json:"headless,omitempty"`
	Nodes          int32                  `protobuf:"varint,4,opt,name=nodes,proto3" json:"nodes,omitempty"`
	EnableEfa      bool                   `protobuf:"varint,5,opt,name=enable_efa,json=enableEfa,proto3" json:"enable_efa,omitempty"`
	PlacementGroup string                 `protobuf:"bytes,6,opt,name=placement_group,json=placementGroup,proto3" json:"placement_group,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FunctionInvokeGangRequest) Reset() {
	*x = FunctionInvokeGangRequest{}
	mi := &file_function_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionInvokeGangRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInvokeGangRequest) ProtoMessage() {}

func (x *FunctionInvokeGangRequest) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInvokeGangRequest.ProtoReflect.Descriptor instead.
func (*FunctionInvokeGangRequest) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{10}
}

func (x *FunctionInvokeGangRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *FunctionInvokeGangRequest) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *FunctionInvokeGangRequest) GetHeadless() bool {
	if x != nil {
		return x.Headless
	}
	return false
}

func (x *FunctionInvokeGangRequest) GetNodes() int32 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

func (x *FunctionInvokeGangRequest) GetEnableEfa() bool {
	if x != nil {
		return x.EnableEfa
	}
	return false
}

func (x *FunctionInvokeGangRequest) GetPlacementGroup() string {
	if x != nil {
		return x.PlacementGroup
	}
	return ""
}

type FunctionInvokeGangResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Result        []byte                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionInvokeGangResponse) Reset() {
	*x = FunctionInvokeGangResponse{}
	mi := &file_function_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionInvokeGangResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInvokeGangResponse) ProtoMessage() {}

func (x *FunctionInvokeGangResponse) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInvokeGangResponse.ProtoReflect.Descriptor instead.
func (*FunctionInvokeGangResponse) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{11}
}

func (x *FunctionInvokeGangResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *FunctionInvokeGangResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *FunctionInvokeGangResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *FunctionInvokeGangResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *FunctionInvokeGangResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_function_proto protoreflect.FileDescriptor

const file_function_proto_rawDesc = "" +
	"\n" +
	"\x0efunction.proto\x12\bfunction\"`\n" +
	"\x15FunctionInvokeRequest\x12\x17\n" +
	"\astub_id\x18\x01 \x01(\tR\x06stubId\x12\x12\n" +
	"\x04args\x18\x02 \x01(\fR\x04args\x12\x1a\n" +
	"\bheadless\x18\x03 \x01(\bR\bheadless\"\x92\x01\n" +
	"\x16FunctionInvokeResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06result\x18\x05 \x01(\fR\x06result\"1\n" +
	"\x16FunctionGetArgsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"=\n" +
	"\x17FunctionGetArgsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x12\n" +
	"\x04args\x18\x02 \x01(\fR\x04args\"K\n" +
	"\x18FunctionSetResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06result\"+\n" +
	"\x19FunctionSetResultResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"m\n" +
	"\x16FunctionMonitorRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\astub_id\x18\x02 \x01(\tR\x06stubId\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\"\x80\x01\n" +
	"\x17FunctionMonitorResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1c\n" +
	"\tcancelled\x18\x02 \x01(\bR\tcancelled\x12\x1a\n" +
	"\bcomplete\x18\x03 \x01(\bR\bcomplete\x12\x1b\n" +
	"\ttimed_out\x18\x04 \x01(\bR\btimedOut\"k\n" +
	"\x17FunctionScheduleRequest\x12\x17\n" +
	"\astub_id\x18\x01 \x01(\tR\x06stubId\x12\x12\n" +
	"\x04when\x18\x02 \x01(\tR\x04when\x12#\n" +
	"\rdeployment_id\x18\x03 \x01(\tR\fdeploymentId\"m\n" +
	"\x18FunctionScheduleResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12(\n" +
	"\x10scheduled_job_id\x18\x03 \x01(\tR\x0escheduledJobId\"\xc2\x01\n" +
	"\x19FunctionInvokeGangRequest\x12\x17\n" +
	"\astub_id\x18\x01 \x01(\tR\x06stubId\x12\x12\n" +
	"\x04args\x18\x02 \x01(\fR\x04args\x12\x1a\n" +
	"\bheadless\x18\x03 \x01(\bR\bheadless\x12\x14\n" +
	"\x05nodes\x18\x04 \x01(\x05R\x05nodes\x12\x1d\n" +
	"\n" +
	"enable_efa\x18\x05 \x01(\bR\tenableEfa\x12'\n" +
	"\x0fplacement_group\x18\x06 \x01(\tR\x0eplacementGroup\"\x98\x01\n" +
	"\x1aFunctionInvokeGangResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06result\x18\x05 \x01(\fR\x06result2\xc0\x04\n" +
	"\x0fFunctionService\x12W\n" +
	"\x0eFunctionInvoke\x12\x1f.function.FunctionInvokeRequest\x1a .function.FunctionInvokeResponse\"\x000\x01\x12c\n" +
	"\x12FunctionInvokeGang\x12#.function.FunctionInvokeGangRequest\x1a$.function.FunctionInvokeGangResponse\"\x000\x01\x12X\n" +
	"\x0fFunctionGetArgs\x12 .function.FunctionGetArgsRequest\x1a!.function.FunctionGetArgsResponse\"\x00\x12^\n" +
	"\x11FunctionSetResult\x12\".function.FunctionSetResultRequest\x1a#.function.FunctionSetResultResponse\"\x00\x12X\n" +
	"\x0fFunctionMonitor\x12 .function.FunctionMonitorRequest\x1a!.function.FunctionMonitorResponse0\x01\x12[\n" +
	"\x10FunctionSchedule\x12!.function.FunctionScheduleRequest\x1a\".function.FunctionScheduleResponse\"\x00B#Z!github.com/beam-cloud/beta9/protob\x06proto3"

var (
	file_function_proto_rawDescOnce sync.Once
	file_function_proto_rawDescData []byte
)

func file_function_proto_rawDescGZIP() []byte {
	file_function_proto_rawDescOnce.Do(func() {
		file_function_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_function_proto_rawDesc), len(file_function_proto_rawDesc)))
	})
	return file_function_proto_rawDescData
}

var file_function_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_function_proto_goTypes = []any{
	(*FunctionInvokeRequest)(nil),      // 0: function.FunctionInvokeRequest
	(*FunctionInvokeResponse)(nil),     // 1: function.FunctionInvokeResponse
	(*FunctionGetArgsRequest)(nil),     // 2: function.FunctionGetArgsRequest
	(*FunctionGetArgsResponse)(nil),    // 3: function.FunctionGetArgsResponse
	(*FunctionSetResultRequest)(nil),   // 4: function.FunctionSetResultRequest
	(*FunctionSetResultResponse)(nil),  // 5: function.FunctionSetResultResponse
	(*FunctionMonitorRequest)(nil),     // 6: function.FunctionMonitorRequest
	(*FunctionMonitorResponse)(nil),    // 7: function.FunctionMonitorResponse
	(*FunctionScheduleRequest)(nil),    // 8: function.FunctionScheduleRequest
	(*FunctionScheduleResponse)(nil),   // 9: function.FunctionScheduleResponse
	(*FunctionInvokeGangRequest)(nil),  // 10: function.FunctionInvokeGangRequest
	(*FunctionInvokeGangResponse)(nil), // 11: function.FunctionInvokeGangResponse
}
var file_function_proto_depIdxs = []int32{
	0,  // 0: function.FunctionService.FunctionInvoke:input_type -> function.FunctionInvokeRequest
	10, // 1: function.FunctionService.FunctionInvokeGang:input_type -> function.FunctionInvokeGangRequest
	2,  // 2: function.FunctionService.FunctionGetArgs:input_type -> function.FunctionGetArgsRequest
	4,  // 3: function.FunctionService.FunctionSetResult:input_type -> function.FunctionSetResultRequest
	6,  // 4: function.FunctionService.FunctionMonitor:input_type -> function.FunctionMonitorRequest
	8,  // 5: function.FunctionService.FunctionSchedule:input_type -> function.FunctionScheduleRequest
	1,  // 6: function.FunctionService.FunctionInvoke:output_type -> function.FunctionInvokeResponse
	11, // 7: function.FunctionService.FunctionInvokeGang:output_type -> function.FunctionInvokeGangResponse
	3,  // 8: function.FunctionService.FunctionGetArgs:output_type -> function.FunctionGetArgsResponse
	5,  // 9: function.FunctionService.FunctionSetResult:output_type -> function.FunctionSetResultResponse
	7,  // 10: function.FunctionService.FunctionMonitor:output_type -> function.FunctionMonitorResponse
	9,  // 11: function.FunctionService.FunctionSchedule:output_type -> function.FunctionScheduleResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_function_proto_init() }
func file_function_proto_init() {
	if File_function_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_function_proto_rawDesc), len(file_function_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_function_proto_goTypes,
		DependencyIndexes: file_function_proto_depIdxs,
		MessageInfos:      file_function_proto_msgTypes,
	}.Build()
	File_function_proto = out.File
	file_function_proto_goTypes = nil
	file_function_proto_depIdxs = nil
}
