// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: image.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildStep) Reset() {
	*x = BuildStep{}
	mi := &file_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStep) ProtoMessage() {}

func (x *BuildStep) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStep.ProtoReflect.Descriptor instead.
func (*BuildStep) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{0}
}

func (x *BuildStep) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BuildStep) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type VerifyImageBuildRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PythonVersion    string                 `protobuf:"bytes,1,opt,name=python_version,json=pythonVersion,proto3" json:"python_version,omitempty"`
	PythonPackages   []string               `protobuf:"bytes,2,rep,name=python_packages,json=pythonPackages,proto3" json:"python_packages,omitempty"`
	Commands         []string               `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"`
	ForceRebuild     bool                   `protobuf:"varint,4,opt,name=force_rebuild,json=forceRebuild,proto3" json:"force_rebuild,omitempty"`
	ExistingImageUri string                 `protobuf:"bytes,5,opt,name=existing_image_uri,json=existingImageUri,proto3" json:"existing_image_uri,omitempty"`
	BuildSteps       []*BuildStep           `protobuf:"bytes,6,rep,name=build_steps,json=buildSteps,proto3" json:"build_steps,omitempty"`
	EnvVars          []string               `protobuf:"bytes,7,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`
	Dockerfile       string                 `protobuf:"bytes,8,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`
	BuildCtxObject   string                 `protobuf:"bytes,9,opt,name=build_ctx_object,json=buildCtxObject,proto3" json:"build_ctx_object,omitempty"`
	Secrets          []string               `protobuf:"bytes,10,rep,name=secrets,proto3" json:"secrets,omitempty"`
	Gpu              string                 `protobuf:"bytes,11,opt,name=gpu,proto3" json:"gpu,omitempty"`
	IgnorePython     bool                   `protobuf:"varint,12,opt,name=ignore_python,json=ignorePython,proto3" json:"ignore_python,omitempty"`
	ImageId          *string                `protobuf:"bytes,13,opt,name=image_id,json=imageId,proto3,oneof" json:"image_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifyImageBuildRequest) Reset() {
	*x = VerifyImageBuildRequest{}
	mi := &file_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyImageBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyImageBuildRequest) ProtoMessage() {}

func (x *VerifyImageBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyImageBuildRequest.ProtoReflect.Descriptor instead.
func (*VerifyImageBuildRequest) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyImageBuildRequest) GetPythonVersion() string {
	if x != nil {
		return x.PythonVersion
	}
	return ""
}

func (x *VerifyImageBuildRequest) GetPythonPackages() []string {
	if x != nil {
		return x.PythonPackages
	}
	return nil
}

func (x *VerifyImageBuildRequest) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *VerifyImageBuildRequest) GetForceRebuild() bool {
	if x != nil {
		return x.ForceRebuild
	}
	return false
}

func (x *VerifyImageBuildRequest) GetExistingImageUri() string {
	if x != nil {
		return x.ExistingImageUri
	}
	return ""
}

func (x *VerifyImageBuildRequest) GetBuildSteps() []*BuildStep {
	if x != nil {
		return x.BuildSteps
	}
	return nil
}

func (x *VerifyImageBuildRequest) GetEnvVars() []string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *VerifyImageBuildRequest) GetDockerfile() string {
	if x != nil {
		return x.Dockerfile
	}
	return ""
}

func (x *VerifyImageBuildRequest) GetBuildCtxObject() string {
	if x != nil {
		return x.BuildCtxObject
	}
	return ""
}

func (x *VerifyImageBuildRequest) GetSecrets() []string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *VerifyImageBuildRequest) GetGpu() string {
	if x != nil {
		return x.Gpu
	}
	return ""
}

func (x *VerifyImageBuildRequest) GetIgnorePython() bool {
	if x != nil {
		return x.IgnorePython
	}
	return false
}

func (x *VerifyImageBuildRequest) GetImageId() string {
	if x != nil && x.ImageId != nil {
		return *x.ImageId
	}
	return ""
}

type VerifyImageBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Exists        bool                   `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyImageBuildResponse) Reset() {
	*x = VerifyImageBuildResponse{}
	mi := &file_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyImageBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyImageBuildResponse) ProtoMessage() {}

func (x *VerifyImageBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyImageBuildResponse.ProtoReflect.Descriptor instead.
func (*VerifyImageBuildResponse) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyImageBuildResponse) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *VerifyImageBuildResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyImageBuildResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type BuildImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// These parameters are used for a "beta9" managed image
	PythonVersion  string   `protobuf:"bytes,1,opt,name=python_version,json=pythonVersion,proto3" json:"python_version,omitempty"`
	PythonPackages []string `protobuf:"bytes,2,rep,name=python_packages,json=pythonPackages,proto3" json:"python_packages,omitempty"`
	Commands       []string `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"`
	// These parameters are used for an existing image
	ExistingImageUri   string            `protobuf:"bytes,4,opt,name=existing_image_uri,json=existingImageUri,proto3" json:"existing_image_uri,omitempty"` // URI for an existing image in the format
	ExistingImageCreds map[string]string `protobuf:"bytes,5,rep,name=existing_image_creds,json=existingImageCreds,proto3" json:"existing_image_creds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BuildSteps         []*BuildStep      `protobuf:"bytes,6,rep,name=build_steps,json=buildSteps,proto3" json:"build_steps,omitempty"`
	EnvVars            []string          `protobuf:"bytes,7,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`
	Dockerfile         string            `protobuf:"bytes,8,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`
	BuildCtxObject     string            `protobuf:"bytes,9,opt,name=build_ctx_object,json=buildCtxObject,proto3" json:"build_ctx_object,omitempty"`
	Secrets            []string          `protobuf:"bytes,10,rep,name=secrets,proto3" json:"secrets,omitempty"`
	Gpu                string            `protobuf:"bytes,11,opt,name=gpu,proto3" json:"gpu,omitempty"`
	IgnorePython       bool              `protobuf:"varint,12,opt,name=ignore_python,json=ignorePython,proto3" json:"ignore_python,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BuildImageRequest) Reset() {
	*x = BuildImageRequest{}
	mi := &file_image_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildImageRequest) ProtoMessage() {}

func (x *BuildImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildImageRequest.ProtoReflect.Descriptor instead.
func (*BuildImageRequest) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{3}
}

func (x *BuildImageRequest) GetPythonVersion() string {
	if x != nil {
		return x.PythonVersion
	}
	return ""
}

func (x *BuildImageRequest) GetPythonPackages() []string {
	if x != nil {
		return x.PythonPackages
	}
	return nil
}

func (x *BuildImageRequest) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *BuildImageRequest) GetExistingImageUri() string {
	if x != nil {
		return x.ExistingImageUri
	}
	return ""
}

func (x *BuildImageRequest) GetExistingImageCreds() map[string]string {
	if x != nil {
		return x.ExistingImageCreds
	}
	return nil
}

func (x *BuildImageRequest) GetBuildSteps() []*BuildStep {
	if x != nil {
		return x.BuildSteps
	}
	return nil
}

func (x *BuildImageRequest) GetEnvVars() []string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *BuildImageRequest) GetDockerfile() string {
	if x != nil {
		return x.Dockerfile
	}
	return ""
}

func (x *BuildImageRequest) GetBuildCtxObject() string {
	if x != nil {
		return x.BuildCtxObject
	}
	return ""
}

func (x *BuildImageRequest) GetSecrets() []string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *BuildImageRequest) GetGpu() string {
	if x != nil {
		return x.Gpu
	}
	return ""
}

func (x *BuildImageRequest) GetIgnorePython() bool {
	if x != nil {
		return x.IgnorePython
	}
	return false
}

type BuildImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	PythonVersion string                 `protobuf:"bytes,5,opt,name=python_version,json=pythonVersion,proto3" json:"python_version,omitempty"`
	Warning       bool                   `protobuf:"varint,6,opt,name=warning,proto3" json:"warning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildImageResponse) Reset() {
	*x = BuildImageResponse{}
	mi := &file_image_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildImageResponse) ProtoMessage() {}

func (x *BuildImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildImageResponse.ProtoReflect.Descriptor instead.
func (*BuildImageResponse) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{4}
}

func (x *BuildImageResponse) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *BuildImageResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BuildImageResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *BuildImageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuildImageResponse) GetPythonVersion() string {
	if x != nil {
		return x.PythonVersion
	}
	return ""
}

func (x *BuildImageResponse) GetWarning() bool {
	if x != nil {
		return x.Warning
	}
	return false
}

var File_image_proto protoreflect.FileDescriptor

const file_image_proto_rawDesc = "" +
	"\n" +
	"\vimage.proto\x12\x05image\x1a\x1cgoogle/api/annotations.proto\"9\n" +
	"\tBuildStep\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"\xee\x03\n" +
	"\x17VerifyImageBuildRequest\x12%\n" +
	"\x0epython_version\x18\x01 \x01(\tR\rpythonVersion\x12'\n" +
	"\x0fpython_packages\x18\x02 \x03(\tR\x0epythonPackages\x12\x1a\n" +
	"\bcommands\x18\x03 \x03(\tR\bcommands\x12#\n" +
	"\rforce_rebuild\x18\x04 \x01(\bR\fforceRebuild\x12,\n" +
	"\x12existing_image_uri\x18\x05 \x01(\tR\x10existingImageUri\x121\n" +
	"\vbuild_steps\x18\x06 \x03(\v2\x10.image.BuildStepR\n" +
	"buildSteps\x12\x19\n" +
	"\benv_vars\x18\a \x03(\tR\aenvVars\x12\x1e\n" +
	"\n" +
	"dockerfile\x18\b \x01(\tR\n" +
	"dockerfile\x12(\n" +
	"\x10build_ctx_object\x18\t \x01(\tR\x0ebuildCtxObject\x12\x18\n" +
	"\asecrets\x18\n" +
	" \x03(\tR\asecrets\x12\x10\n" +
	"\x03gpu\x18\v \x01(\tR\x03gpu\x12#\n" +
	"\rignore_python\x18\f \x01(\bR\fignorePython\x12\x1e\n" +
	"\bimage_id\x18\r \x01(\tH\x00R\aimageId\x88\x01\x01B\v\n" +
	"\t_image_id\"c\n" +
	"\x18VerifyImageBuildResponse\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\x12\x16\n" +
	"\x06exists\x18\x03 \x01(\bR\x06exists\"\xc1\x04\n" +
	"\x11BuildImageRequest\x12%\n" +
	"\x0epython_version\x18\x01 \x01(\tR\rpythonVersion\x12'\n" +
	"\x0fpython_packages\x18\x02 \x03(\tR\x0epythonPackages\x12\x1a\n" +
	"\bcommands\x18\x03 \x03(\tR\bcommands\x12,\n" +
	"\x12existing_image_uri\x18\x04 \x01(\tR\x10existingImageUri\x12b\n" +
	"\x14existing_image_creds\x18\x05 \x03(\v20.image.BuildImageRequest.ExistingImageCredsEntryR\x12existingImageCreds\x121\n" +
	"\vbuild_steps\x18\x06 \x03(\v2\x10.image.BuildStepR\n" +
	"buildSteps\x12\x19\n" +
	"\benv_vars\x18\a \x03(\tR\aenvVars\x12\x1e\n" +
	"\n" +
	"dockerfile\x18\b \x01(\tR\n" +
	"dockerfile\x12(\n" +
	"\x10build_ctx_object\x18\t \x01(\tR\x0ebuildCtxObject\x12\x18\n" +
	"\asecrets\x18\n" +
	" \x03(\tR\asecrets\x12\x10\n" +
	"\x03gpu\x18\v \x01(\tR\x03gpu\x12#\n" +
	"\rignore_python\x18\f \x01(\bR\fignorePython\x1aE\n" +
	"\x17ExistingImageCredsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x01\n" +
	"\x12BuildImageResponse\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12%\n" +
	"\x0epython_version\x18\x05 \x01(\tR\rpythonVersion\x12\x18\n" +
	"\awarning\x18\x06 \x01(\bR\awarning2\xe3\x01\n" +
	"\fImageService\x12t\n" +
	"\x10VerifyImageBuild\x12\x1e.image.VerifyImageBuildRequest\x1a\x1f.image.VerifyImageBuildResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/images/verify-build\x12]\n" +
	"\n" +
	"BuildImage\x12\x18.image.BuildImageRequest\x1a\x19.image.BuildImageResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/images/build0\x01B#Z!github.com/beam-cloud/beta9/protob\x06proto3"

var (
	file_image_proto_rawDescOnce sync.Once
	file_image_proto_rawDescData []byte
)

func file_image_proto_rawDescGZIP() []byte {
	file_image_proto_rawDescOnce.Do(func() {
		file_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_image_proto_rawDesc), len(file_image_proto_rawDesc)))
	})
	return file_image_proto_rawDescData
}

var file_image_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_image_proto_goTypes = []any{
	(*BuildStep)(nil),                // 0: image.BuildStep
	(*VerifyImageBuildRequest)(nil),  // 1: image.VerifyImageBuildRequest
	(*VerifyImageBuildResponse)(nil), // 2: image.VerifyImageBuildResponse
	(*BuildImageRequest)(nil),        // 3: image.BuildImageRequest
	(*BuildImageResponse)(nil),       // 4: image.BuildImageResponse
	nil,                              // 5: image.BuildImageRequest.ExistingImageCredsEntry
}
var file_image_proto_depIdxs = []int32{
	0, // 0: image.VerifyImageBuildRequest.build_steps:type_name -> image.BuildStep
	5, // 1: image.BuildImageRequest.existing_image_creds:type_name -> image.BuildImageRequest.ExistingImageCredsEntry
	0, // 2: image.BuildImageRequest.build_steps:type_name -> image.BuildStep
	1, // 3: image.ImageService.VerifyImageBuild:input_type -> image.VerifyImageBuildRequest
	3, // 4: image.ImageService.BuildImage:input_type -> image.BuildImageRequest
	2, // 5: image.ImageService.VerifyImageBuild:output_type -> image.VerifyImageBuildResponse
	4, // 6: image.ImageService.BuildImage:output_type -> image.BuildImageResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_image_proto_init() }
func file_image_proto_init() {
	if File_image_proto != nil {
		return
	}
	file_image_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_image_proto_rawDesc), len(file_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_image_proto_goTypes,
		DependencyIndexes: file_image_proto_depIdxs,
		MessageInfos:      file_image_proto_msgTypes,
	}.Build()
	File_image_proto = out.File
	file_image_proto_goTypes = nil
	file_image_proto_depIdxs = nil
}
