// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: output.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutputSaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputSaveRequest) Reset() {
	*x = OutputSaveRequest{}
	mi := &file_output_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputSaveRequest) ProtoMessage() {}

func (x *OutputSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_output_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputSaveRequest.ProtoReflect.Descriptor instead.
func (*OutputSaveRequest) Descriptor() ([]byte, []int) {
	return file_output_proto_rawDescGZIP(), []int{0}
}

func (x *OutputSaveRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *OutputSaveRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *OutputSaveRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type OutputSaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputSaveResponse) Reset() {
	*x = OutputSaveResponse{}
	mi := &file_output_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputSaveResponse) ProtoMessage() {}

func (x *OutputSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_output_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputSaveResponse.ProtoReflect.Descriptor instead.
func (*OutputSaveResponse) Descriptor() ([]byte, []int) {
	return file_output_proto_rawDescGZIP(), []int{1}
}

func (x *OutputSaveResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OutputSaveResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *OutputSaveResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OutputStatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputStatRequest) Reset() {
	*x = OutputStatRequest{}
	mi := &file_output_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputStatRequest) ProtoMessage() {}

func (x *OutputStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_output_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputStatRequest.ProtoReflect.Descriptor instead.
func (*OutputStatRequest) Descriptor() ([]byte, []int) {
	return file_output_proto_rawDescGZIP(), []int{2}
}

func (x *OutputStatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OutputStatRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *OutputStatRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type OutputStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Atime         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=atime,proto3" json:"atime,omitempty"`
	Mtime         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=mtime,proto3" json:"mtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputStat) Reset() {
	*x = OutputStat{}
	mi := &file_output_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputStat) ProtoMessage() {}

func (x *OutputStat) ProtoReflect() protoreflect.Message {
	mi := &file_output_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputStat.ProtoReflect.Descriptor instead.
func (*OutputStat) Descriptor() ([]byte, []int) {
	return file_output_proto_rawDescGZIP(), []int{3}
}

func (x *OutputStat) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *OutputStat) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *OutputStat) GetAtime() *timestamppb.Timestamp {
	if x != nil {
		return x.Atime
	}
	return nil
}

func (x *OutputStat) GetMtime() *timestamppb.Timestamp {
	if x != nil {
		return x.Mtime
	}
	return nil
}

type OutputStatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Stat          *OutputStat            `protobuf:"bytes,3,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputStatResponse) Reset() {
	*x = OutputStatResponse{}
	mi := &file_output_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputStatResponse) ProtoMessage() {}

func (x *OutputStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_output_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputStatResponse.ProtoReflect.Descriptor instead.
func (*OutputStatResponse) Descriptor() ([]byte, []int) {
	return file_output_proto_rawDescGZIP(), []int{4}
}

func (x *OutputStatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OutputStatResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *OutputStatResponse) GetStat() *OutputStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type OutputPublicURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Expires       uint32                 `protobuf:"varint,4,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputPublicURLRequest) Reset() {
	*x = OutputPublicURLRequest{}
	mi := &file_output_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputPublicURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputPublicURLRequest) ProtoMessage() {}

func (x *OutputPublicURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_output_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputPublicURLRequest.ProtoReflect.Descriptor instead.
func (*OutputPublicURLRequest) Descriptor() ([]byte, []int) {
	return file_output_proto_rawDescGZIP(), []int{5}
}

func (x *OutputPublicURLRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OutputPublicURLRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *OutputPublicURLRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *OutputPublicURLRequest) GetExpires() uint32 {
	if x != nil {
		return x.Expires
	}
	return 0
}

type OutputPublicURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,3,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputPublicURLResponse) Reset() {
	*x = OutputPublicURLResponse{}
	mi := &file_output_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputPublicURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputPublicURLResponse) ProtoMessage() {}

func (x *OutputPublicURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_output_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputPublicURLResponse.ProtoReflect.Descriptor instead.
func (*OutputPublicURLResponse) Descriptor() ([]byte, []int) {
	return file_output_proto_rawDescGZIP(), []int{6}
}

func (x *OutputPublicURLResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OutputPublicURLResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *OutputPublicURLResponse) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

var File_output_proto protoreflect.FileDescriptor

const file_output_proto_rawDesc = "" +
	"\n" +
	"\foutput.proto\x12\x06output\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n" +
	"\x11OutputSaveRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"M\n" +
	"\x12OutputSaveResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"X\n" +
	"\x11OutputStatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\"\x98\x01\n" +
	"\n" +
	"OutputStat\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x120\n" +
	"\x05atime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05atime\x120\n" +
	"\x05mtime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05mtime\"e\n" +
	"\x12OutputStatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12&\n" +
	"\x04stat\x18\x03 \x01(\v2\x12.output.OutputStatR\x04stat\"w\n" +
	"\x16OutputPublicURLRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x18\n" +
	"\aexpires\x18\x04 \x01(\rR\aexpires\"a\n" +
	"\x17OutputPublicURLResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12\x1d\n" +
	"\n" +
	"public_url\x18\x03 \x01(\tR\tpublicUrl2\xfb\x01\n" +
	"\rOutputService\x12M\n" +
	"\x10OutputSaveStream\x12\x19.output.OutputSaveRequest\x1a\x1a.output.OutputSaveResponse\"\x00(\x01\x12E\n" +
	"\n" +
	"OutputStat\x12\x19.output.OutputStatRequest\x1a\x1a.output.OutputStatResponse\"\x00\x12T\n" +
	"\x0fOutputPublicURL\x12\x1e.output.OutputPublicURLRequest\x1a\x1f.output.OutputPublicURLResponse\"\x00B#Z!github.com/beam-cloud/beta9/protob\x06proto3"

var (
	file_output_proto_rawDescOnce sync.Once
	file_output_proto_rawDescData []byte
)

func file_output_proto_rawDescGZIP() []byte {
	file_output_proto_rawDescOnce.Do(func() {
		file_output_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_output_proto_rawDesc), len(file_output_proto_rawDesc)))
	})
	return file_output_proto_rawDescData
}

var file_output_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_output_proto_goTypes = []any{
	(*OutputSaveRequest)(nil),       // 0: output.OutputSaveRequest
	(*OutputSaveResponse)(nil),      // 1: output.OutputSaveResponse
	(*OutputStatRequest)(nil),       // 2: output.OutputStatRequest
	(*OutputStat)(nil),              // 3: output.OutputStat
	(*OutputStatResponse)(nil),      // 4: output.OutputStatResponse
	(*OutputPublicURLRequest)(nil),  // 5: output.OutputPublicURLRequest
	(*OutputPublicURLResponse)(nil), // 6: output.OutputPublicURLResponse
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
}
var file_output_proto_depIdxs = []int32{
	7, // 0: output.OutputStat.atime:type_name -> google.protobuf.Timestamp
	7, // 1: output.OutputStat.mtime:type_name -> google.protobuf.Timestamp
	3, // 2: output.OutputStatResponse.stat:type_name -> output.OutputStat
	0, // 3: output.OutputService.OutputSaveStream:input_type -> output.OutputSaveRequest
	2, // 4: output.OutputService.OutputStat:input_type -> output.OutputStatRequest
	5, // 5: output.OutputService.OutputPublicURL:input_type -> output.OutputPublicURLRequest
	1, // 6: output.OutputService.OutputSaveStream:output_type -> output.OutputSaveResponse
	4, // 7: output.OutputService.OutputStat:output_type -> output.OutputStatResponse
	6, // 8: output.OutputService.OutputPublicURL:output_type -> output.OutputPublicURLResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_output_proto_init() }
func file_output_proto_init() {
	if File_output_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_output_proto_rawDesc), len(file_output_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_output_proto_goTypes,
		DependencyIndexes: file_output_proto_depIdxs,
		MessageInfos:      file_output_proto_msgTypes,
	}.Build()
	File_output_proto = out.File
	file_output_proto_goTypes = nil
	file_output_proto_depIdxs = nil
}
