// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: scheduler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RunContainerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContainerId     string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Env             []string               `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty"`
	EntryPoint      []string               `protobuf:"bytes,3,rep,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	Cpu             string                 `protobuf:"bytes,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory          string                 `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Gpu             string                 `protobuf:"bytes,6,opt,name=gpu,proto3" json:"gpu,omitempty"`
	ImageId         string                 `protobuf:"bytes,10,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ScheduleTimeout float32                `protobuf:"fixed32,12,opt,name=schedule_timeout,json=scheduleTimeout,proto3" json:"schedule_timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunContainerRequest) Reset() {
	*x = RunContainerRequest{}
	mi := &file_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunContainerRequest) ProtoMessage() {}

func (x *RunContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunContainerRequest.ProtoReflect.Descriptor instead.
func (*RunContainerRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *RunContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RunContainerRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunContainerRequest) GetEntryPoint() []string {
	if x != nil {
		return x.EntryPoint
	}
	return nil
}

func (x *RunContainerRequest) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *RunContainerRequest) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *RunContainerRequest) GetGpu() string {
	if x != nil {
		return x.Gpu
	}
	return ""
}

func (x *RunContainerRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *RunContainerRequest) GetScheduleTimeout() float32 {
	if x != nil {
		return x.ScheduleTimeout
	}
	return 0
}

type ContainerRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Env           []string               `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty"`
	EntryPoint    []string               `protobuf:"bytes,3,rep,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	Cpu           string                 `protobuf:"bytes,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Gpu           string                 `protobuf:"bytes,6,opt,name=gpu,proto3" json:"gpu,omitempty"`
	ImageId       string                 `protobuf:"bytes,7,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	GpuCount      uint32                 `protobuf:"varint,8,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	StubId        string                 `protobuf:"bytes,9,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,10,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerRequestProto) Reset() {
	*x = ContainerRequestProto{}
	mi := &file_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRequestProto) ProtoMessage() {}

func (x *ContainerRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerRequestProto.ProtoReflect.Descriptor instead.
func (*ContainerRequestProto) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerRequestProto) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerRequestProto) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContainerRequestProto) GetEntryPoint() []string {
	if x != nil {
		return x.EntryPoint
	}
	return nil
}

func (x *ContainerRequestProto) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ContainerRequestProto) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *ContainerRequestProto) GetGpu() string {
	if x != nil {
		return x.Gpu
	}
	return ""
}

func (x *ContainerRequestProto) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ContainerRequestProto) GetGpuCount() uint32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *ContainerRequestProto) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *ContainerRequestProto) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type RunGangRequest struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	GroupId           string                   `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	NodeCount         int32                    `protobuf:"varint,2,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	ContainerRequests []*ContainerRequestProto `protobuf:"bytes,3,rep,name=container_requests,json=containerRequests,proto3" json:"container_requests,omitempty"`
	PlacementGroup    string                   `protobuf:"bytes,4,opt,name=placement_group,json=placementGroup,proto3" json:"placement_group,omitempty"`
	EnableEfa         bool                     `protobuf:"varint,5,opt,name=enable_efa,json=enableEfa,proto3" json:"enable_efa,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RunGangRequest) Reset() {
	*x = RunGangRequest{}
	mi := &file_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunGangRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunGangRequest) ProtoMessage() {}

func (x *RunGangRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunGangRequest.ProtoReflect.Descriptor instead.
func (*RunGangRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *RunGangRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RunGangRequest) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *RunGangRequest) GetContainerRequests() []*ContainerRequestProto {
	if x != nil {
		return x.ContainerRequests
	}
	return nil
}

func (x *RunGangRequest) GetPlacementGroup() string {
	if x != nil {
		return x.PlacementGroup
	}
	return ""
}

func (x *RunGangRequest) GetEnableEfa() bool {
	if x != nil {
		return x.EnableEfa
	}
	return false
}

type RunGangResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	GroupId       string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunGangResponse) Reset() {
	*x = RunGangResponse{}
	mi := &file_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunGangResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunGangResponse) ProtoMessage() {}

func (x *RunGangResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunGangResponse.ProtoReflect.Descriptor instead.
func (*RunGangResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *RunGangResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RunGangResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunGangResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type RunContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunContainerResponse) Reset() {
	*x = RunContainerResponse{}
	mi := &file_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunContainerResponse) ProtoMessage() {}

func (x *RunContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunContainerResponse.ProtoReflect.Descriptor instead.
func (*RunContainerResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *RunContainerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RunContainerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x0fscheduler.proto\x12\tscheduler\"\x10\n" +
	"\x0eVersionRequest\"+\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\xed\x01\n" +
	"\x13RunContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x10\n" +
	"\x03env\x18\x02 \x03(\tR\x03env\x12\x1f\n" +
	"\ventry_point\x18\x03 \x03(\tR\n" +
	"entryPoint\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\tR\x06memory\x12\x10\n" +
	"\x03gpu\x18\x06 \x01(\tR\x03gpu\x12\x19\n" +
	"\bimage_id\x18\n" +
	" \x01(\tR\aimageId\x12)\n" +
	"\x10schedule_timeout\x18\f \x01(\x02R\x0fscheduleTimeout\"\x9d\x02\n" +
	"\x15ContainerRequestProto\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x10\n" +
	"\x03env\x18\x02 \x03(\tR\x03env\x12\x1f\n" +
	"\ventry_point\x18\x03 \x03(\tR\n" +
	"entryPoint\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\tR\x06memory\x12\x10\n" +
	"\x03gpu\x18\x06 \x01(\tR\x03gpu\x12\x19\n" +
	"\bimage_id\x18\a \x01(\tR\aimageId\x12\x1b\n" +
	"\tgpu_count\x18\b \x01(\rR\bgpuCount\x12\x17\n" +
	"\astub_id\x18\t \x01(\tR\x06stubId\x12!\n" +
	"\fworkspace_id\x18\n" +
	" \x01(\tR\vworkspaceId\"\xe3\x01\n" +
	"\x0eRunGangRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"node_count\x18\x02 \x01(\x05R\tnodeCount\x12O\n" +
	"\x12container_requests\x18\x03 \x03(\v2 .scheduler.ContainerRequestProtoR\x11containerRequests\x12'\n" +
	"\x0fplacement_group\x18\x04 \x01(\tR\x0eplacementGroup\x12\x1d\n" +
	"\n" +
	"enable_efa\x18\x05 \x01(\bR\tenableEfa\"\\\n" +
	"\x0fRunGangResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\"F\n" +
	"\x14RunContainerResponse\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xe9\x01\n" +
	"\tScheduler\x12E\n" +
	"\n" +
	"GetVersion\x12\x19.scheduler.VersionRequest\x1a\x1a.scheduler.VersionResponse\"\x00\x12Q\n" +
	"\fRunContainer\x12\x1e.scheduler.RunContainerRequest\x1a\x1f.scheduler.RunContainerResponse\"\x00\x12B\n" +
	"\aRunGang\x12\x19.scheduler.RunGangRequest\x1a\x1a.scheduler.RunGangResponse\"\x00B#Z!github.com/beam-cloud/beta9/protob\x06proto3"

var (
	file_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_proto_rawDescData []byte
)

func file_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)))
	})
	return file_scheduler_proto_rawDescData
}

var file_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_scheduler_proto_goTypes = []any{
	(*VersionRequest)(nil),        // 0: scheduler.VersionRequest
	(*VersionResponse)(nil),       // 1: scheduler.VersionResponse
	(*RunContainerRequest)(nil),   // 2: scheduler.RunContainerRequest
	(*ContainerRequestProto)(nil), // 3: scheduler.ContainerRequestProto
	(*RunGangRequest)(nil),        // 4: scheduler.RunGangRequest
	(*RunGangResponse)(nil),       // 5: scheduler.RunGangResponse
	(*RunContainerResponse)(nil),  // 6: scheduler.RunContainerResponse
}
var file_scheduler_proto_depIdxs = []int32{
	3, // 0: scheduler.RunGangRequest.container_requests:type_name -> scheduler.ContainerRequestProto
	0, // 1: scheduler.Scheduler.GetVersion:input_type -> scheduler.VersionRequest
	2, // 2: scheduler.Scheduler.RunContainer:input_type -> scheduler.RunContainerRequest
	4, // 3: scheduler.Scheduler.RunGang:input_type -> scheduler.RunGangRequest
	1, // 4: scheduler.Scheduler.GetVersion:output_type -> scheduler.VersionResponse
	6, // 5: scheduler.Scheduler.RunContainer:output_type -> scheduler.RunContainerResponse
	5, // 6: scheduler.Scheduler.RunGang:output_type -> scheduler.RunGangResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scheduler_proto_init() }
func file_scheduler_proto_init() {
	if File_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_proto_depIdxs,
		MessageInfos:      file_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_proto = out.File
	file_scheduler_proto_goTypes = nil
	file_scheduler_proto_depIdxs = nil
}
