// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: shell.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateStandaloneShellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StubId        string                 `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStandaloneShellRequest) Reset() {
	*x = CreateStandaloneShellRequest{}
	mi := &file_shell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStandaloneShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStandaloneShellRequest) ProtoMessage() {}

func (x *CreateStandaloneShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStandaloneShellRequest.ProtoReflect.Descriptor instead.
func (*CreateStandaloneShellRequest) Descriptor() ([]byte, []int) {
	return file_shell_proto_rawDescGZIP(), []int{0}
}

func (x *CreateStandaloneShellRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

type CreateStandaloneShellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,5,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStandaloneShellResponse) Reset() {
	*x = CreateStandaloneShellResponse{}
	mi := &file_shell_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStandaloneShellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStandaloneShellResponse) ProtoMessage() {}

func (x *CreateStandaloneShellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shell_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStandaloneShellResponse.ProtoReflect.Descriptor instead.
func (*CreateStandaloneShellResponse) Descriptor() ([]byte, []int) {
	return file_shell_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStandaloneShellResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CreateStandaloneShellResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CreateStandaloneShellResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateStandaloneShellResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateStandaloneShellResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type CreateShellInExistingContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShellInExistingContainerRequest) Reset() {
	*x = CreateShellInExistingContainerRequest{}
	mi := &file_shell_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShellInExistingContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShellInExistingContainerRequest) ProtoMessage() {}

func (x *CreateShellInExistingContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shell_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShellInExistingContainerRequest.ProtoReflect.Descriptor instead.
func (*CreateShellInExistingContainerRequest) Descriptor() ([]byte, []int) {
	return file_shell_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShellInExistingContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type CreateShellInExistingContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	StubId        string                 `protobuf:"bytes,4,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,5,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShellInExistingContainerResponse) Reset() {
	*x = CreateShellInExistingContainerResponse{}
	mi := &file_shell_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShellInExistingContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShellInExistingContainerResponse) ProtoMessage() {}

func (x *CreateShellInExistingContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shell_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShellInExistingContainerResponse.ProtoReflect.Descriptor instead.
func (*CreateShellInExistingContainerResponse) Descriptor() ([]byte, []int) {
	return file_shell_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShellInExistingContainerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CreateShellInExistingContainerResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateShellInExistingContainerResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateShellInExistingContainerResponse) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *CreateShellInExistingContainerResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_shell_proto protoreflect.FileDescriptor

const file_shell_proto_rawDesc = "" +
	"\n" +
	"\vshell.proto\x12\x05shell\"7\n" +
	"\x1cCreateStandaloneShellRequest\x12\x17\n" +
	"\astub_id\x18\x01 \x01(\tR\x06stubId\"\xa3\x01\n" +
	"\x1dCreateStandaloneShellResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x17\n" +
	"\aerr_msg\x18\x05 \x01(\tR\x06errMsg\"J\n" +
	"%CreateShellInExistingContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"\xa2\x01\n" +
	"&CreateShellInExistingContainerResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x17\n" +
	"\astub_id\x18\x04 \x01(\tR\x06stubId\x12\x17\n" +
	"\aerr_msg\x18\x05 \x01(\tR\x06errMsg2\xf5\x01\n" +
	"\fShellService\x12d\n" +
	"\x15CreateStandaloneShell\x12#.shell.CreateStandaloneShellRequest\x1a$.shell.CreateStandaloneShellResponse\"\x00\x12\x7f\n" +
	"\x1eCreateShellInExistingContainer\x12,.shell.CreateShellInExistingContainerRequest\x1a-.shell.CreateShellInExistingContainerResponse\"\x00B#Z!github.com/beam-cloud/beta9/protob\x06proto3"

var (
	file_shell_proto_rawDescOnce sync.Once
	file_shell_proto_rawDescData []byte
)

func file_shell_proto_rawDescGZIP() []byte {
	file_shell_proto_rawDescOnce.Do(func() {
		file_shell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shell_proto_rawDesc), len(file_shell_proto_rawDesc)))
	})
	return file_shell_proto_rawDescData
}

var file_shell_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shell_proto_goTypes = []any{
	(*CreateStandaloneShellRequest)(nil),           // 0: shell.CreateStandaloneShellRequest
	(*CreateStandaloneShellResponse)(nil),          // 1: shell.CreateStandaloneShellResponse
	(*CreateShellInExistingContainerRequest)(nil),  // 2: shell.CreateShellInExistingContainerRequest
	(*CreateShellInExistingContainerResponse)(nil), // 3: shell.CreateShellInExistingContainerResponse
}
var file_shell_proto_depIdxs = []int32{
	0, // 0: shell.ShellService.CreateStandaloneShell:input_type -> shell.CreateStandaloneShellRequest
	2, // 1: shell.ShellService.CreateShellInExistingContainer:input_type -> shell.CreateShellInExistingContainerRequest
	1, // 2: shell.ShellService.CreateStandaloneShell:output_type -> shell.CreateStandaloneShellResponse
	3, // 3: shell.ShellService.CreateShellInExistingContainer:output_type -> shell.CreateShellInExistingContainerResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shell_proto_init() }
func file_shell_proto_init() {
	if File_shell_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shell_proto_rawDesc), len(file_shell_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shell_proto_goTypes,
		DependencyIndexes: file_shell_proto_depIdxs,
		MessageInfos:      file_shell_proto_msgTypes,
	}.Build()
	File_shell_proto = out.File
	file_shell_proto_goTypes = nil
	file_shell_proto_depIdxs = nil
}
