// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: signal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ttl           int64                  `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalSetRequest) Reset() {
	*x = SignalSetRequest{}
	mi := &file_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalSetRequest) ProtoMessage() {}

func (x *SignalSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalSetRequest.ProtoReflect.Descriptor instead.
func (*SignalSetRequest) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{0}
}

func (x *SignalSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignalSetRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type SignalSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalSetResponse) Reset() {
	*x = SignalSetResponse{}
	mi := &file_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalSetResponse) ProtoMessage() {}

func (x *SignalSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalSetResponse.ProtoReflect.Descriptor instead.
func (*SignalSetResponse) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{1}
}

func (x *SignalSetResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SignalClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalClearRequest) Reset() {
	*x = SignalClearRequest{}
	mi := &file_signal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalClearRequest) ProtoMessage() {}

func (x *SignalClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalClearRequest.ProtoReflect.Descriptor instead.
func (*SignalClearRequest) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{2}
}

func (x *SignalClearRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SignalClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalClearResponse) Reset() {
	*x = SignalClearResponse{}
	mi := &file_signal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalClearResponse) ProtoMessage() {}

func (x *SignalClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalClearResponse.ProtoReflect.Descriptor instead.
func (*SignalClearResponse) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{3}
}

func (x *SignalClearResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SignalMonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalMonitorRequest) Reset() {
	*x = SignalMonitorRequest{}
	mi := &file_signal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMonitorRequest) ProtoMessage() {}

func (x *SignalMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMonitorRequest.ProtoReflect.Descriptor instead.
func (*SignalMonitorRequest) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{4}
}

func (x *SignalMonitorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SignalMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Set           bool                   `protobuf:"varint,2,opt,name=set,proto3" json:"set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalMonitorResponse) Reset() {
	*x = SignalMonitorResponse{}
	mi := &file_signal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMonitorResponse) ProtoMessage() {}

func (x *SignalMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMonitorResponse.ProtoReflect.Descriptor instead.
func (*SignalMonitorResponse) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{5}
}

func (x *SignalMonitorResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SignalMonitorResponse) GetSet() bool {
	if x != nil {
		return x.Set
	}
	return false
}

var File_signal_proto protoreflect.FileDescriptor

const file_signal_proto_rawDesc = "" +
	"\n" +
	"\fsignal.proto\x12\x06signal\"8\n" +
	"\x10SignalSetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\x03R\x03ttl\"#\n" +
	"\x11SignalSetResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"(\n" +
	"\x12SignalClearRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"%\n" +
	"\x13SignalClearResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"*\n" +
	"\x14SignalMonitorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"9\n" +
	"\x15SignalMonitorResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03set\x18\x02 \x01(\bR\x03set2\xed\x01\n" +
	"\rSignalService\x12B\n" +
	"\tSignalSet\x12\x18.signal.SignalSetRequest\x1a\x19.signal.SignalSetResponse\"\x00\x12H\n" +
	"\vSignalClear\x12\x1a.signal.SignalClearRequest\x1a\x1b.signal.SignalClearResponse\"\x00\x12N\n" +
	"\rSignalMonitor\x12\x1c.signal.SignalMonitorRequest\x1a\x1d.signal.SignalMonitorResponse0\x01B#Z!github.com/beam-cloud/beta9/protob\x06proto3"

var (
	file_signal_proto_rawDescOnce sync.Once
	file_signal_proto_rawDescData []byte
)

func file_signal_proto_rawDescGZIP() []byte {
	file_signal_proto_rawDescOnce.Do(func() {
		file_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signal_proto_rawDesc), len(file_signal_proto_rawDesc)))
	})
	return file_signal_proto_rawDescData
}

var file_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_signal_proto_goTypes = []any{
	(*SignalSetRequest)(nil),      // 0: signal.SignalSetRequest
	(*SignalSetResponse)(nil),     // 1: signal.SignalSetResponse
	(*SignalClearRequest)(nil),    // 2: signal.SignalClearRequest
	(*SignalClearResponse)(nil),   // 3: signal.SignalClearResponse
	(*SignalMonitorRequest)(nil),  // 4: signal.SignalMonitorRequest
	(*SignalMonitorResponse)(nil), // 5: signal.SignalMonitorResponse
}
var file_signal_proto_depIdxs = []int32{
	0, // 0: signal.SignalService.SignalSet:input_type -> signal.SignalSetRequest
	2, // 1: signal.SignalService.SignalClear:input_type -> signal.SignalClearRequest
	4, // 2: signal.SignalService.SignalMonitor:input_type -> signal.SignalMonitorRequest
	1, // 3: signal.SignalService.SignalSet:output_type -> signal.SignalSetResponse
	3, // 4: signal.SignalService.SignalClear:output_type -> signal.SignalClearResponse
	5, // 5: signal.SignalService.SignalMonitor:output_type -> signal.SignalMonitorResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_signal_proto_init() }
func file_signal_proto_init() {
	if File_signal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signal_proto_rawDesc), len(file_signal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signal_proto_goTypes,
		DependencyIndexes: file_signal_proto_depIdxs,
		MessageInfos:      file_signal_proto_msgTypes,
	}.Build()
	File_signal_proto = out.File
	file_signal_proto_goTypes = nil
	file_signal_proto_depIdxs = nil
}
