// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: taskqueue.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskQueuePutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StubId        string                 `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskQueuePutRequest) Reset() {
	*x = TaskQueuePutRequest{}
	mi := &file_taskqueue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskQueuePutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskQueuePutRequest) ProtoMessage() {}

func (x *TaskQueuePutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskqueue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskQueuePutRequest.ProtoReflect.Descriptor instead.
func (*TaskQueuePutRequest) Descriptor() ([]byte, []int) {
	return file_taskqueue_proto_rawDescGZIP(), []int{0}
}

func (x *TaskQueuePutRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *TaskQueuePutRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TaskQueuePutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskQueuePutResponse) Reset() {
	*x = TaskQueuePutResponse{}
	mi := &file_taskqueue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskQueuePutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskQueuePutResponse) ProtoMessage() {}

func (x *TaskQueuePutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskqueue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskQueuePutResponse.ProtoReflect.Descriptor instead.
func (*TaskQueuePutResponse) Descriptor() ([]byte, []int) {
	return file_taskqueue_proto_rawDescGZIP(), []int{1}
}

func (x *TaskQueuePutResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TaskQueuePutResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskQueuePopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StubId        string                 `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskQueuePopRequest) Reset() {
	*x = TaskQueuePopRequest{}
	mi := &file_taskqueue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskQueuePopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskQueuePopRequest) ProtoMessage() {}

func (x *TaskQueuePopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskqueue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskQueuePopRequest.ProtoReflect.Descriptor instead.
func (*TaskQueuePopRequest) Descriptor() ([]byte, []int) {
	return file_taskqueue_proto_rawDescGZIP(), []int{2}
}

func (x *TaskQueuePopRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *TaskQueuePopRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type TaskQueuePopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	TaskMsg       []byte                 `protobuf:"bytes,2,opt,name=task_msg,json=taskMsg,proto3" json:"task_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskQueuePopResponse) Reset() {
	*x = TaskQueuePopResponse{}
	mi := &file_taskqueue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskQueuePopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskQueuePopResponse) ProtoMessage() {}

func (x *TaskQueuePopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskqueue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskQueuePopResponse.ProtoReflect.Descriptor instead.
func (*TaskQueuePopResponse) Descriptor() ([]byte, []int) {
	return file_taskqueue_proto_rawDescGZIP(), []int{3}
}

func (x *TaskQueuePopResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TaskQueuePopResponse) GetTaskMsg() []byte {
	if x != nil {
		return x.TaskMsg
	}
	return nil
}

type TaskQueueLengthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StubId        string                 `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskQueueLengthRequest) Reset() {
	*x = TaskQueueLengthRequest{}
	mi := &file_taskqueue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskQueueLengthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskQueueLengthRequest) ProtoMessage() {}

func (x *TaskQueueLengthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskqueue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskQueueLengthRequest.ProtoReflect.Descriptor instead.
func (*TaskQueueLengthRequest) Descriptor() ([]byte, []int) {
	return file_taskqueue_proto_rawDescGZIP(), []int{4}
}

func (x *TaskQueueLengthRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

type TaskQueueLengthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Length        int64                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskQueueLengthResponse) Reset() {
	*x = TaskQueueLengthResponse{}
	mi := &file_taskqueue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskQueueLengthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskQueueLengthResponse) ProtoMessage() {}

func (x *TaskQueueLengthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskqueue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskQueueLengthResponse.ProtoReflect.Descriptor instead.
func (*TaskQueueLengthResponse) Descriptor() ([]byte, []int) {
	return file_taskqueue_proto_rawDescGZIP(), []int{5}
}

func (x *TaskQueueLengthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TaskQueueLengthResponse) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type TaskQueueCompleteRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StubId            string                 `protobuf:"bytes,2,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	TaskDuration      float32                `protobuf:"fixed32,3,opt,name=task_duration,json=taskDuration,proto3" json:"task_duration,omitempty"`
	TaskStatus        string                 `protobuf:"bytes,4,opt,name=task_status,json=taskStatus,proto3" json:"task_status,omitempty"`
	ContainerId       string                 `protobuf:"bytes,5,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerHostname string                 `protobuf:"bytes,6,opt,name=container_hostname,json=containerHostname,proto3" json:"container_hostname,omitempty"`
	KeepWarmSeconds   float32                `protobuf:"fixed32,7,opt,name=keep_warm_seconds,json=keepWarmSeconds,proto3" json:"keep_warm_seconds,omitempty"`
	Result            []byte                 `protobuf:"bytes,8,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskQueueCompleteRequest) Reset() {
	*x = TaskQueueCompleteRequest{}
	mi := &file_taskqueue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskQueueCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskQueueCompleteRequest) ProtoMessage() {}

func (x *TaskQueueCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskqueue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskQueueCompleteRequest.ProtoReflect.Descriptor instead.
func (*TaskQueueCompleteRequest) Descriptor() ([]byte, []int) {
	return file_taskqueue_proto_rawDescGZIP(), []int{6}
}

func (x *TaskQueueCompleteRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskQueueCompleteRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *TaskQueueCompleteRequest) GetTaskDuration() float32 {
	if x != nil {
		return x.TaskDuration
	}
	return 0
}

func (x *TaskQueueCompleteRequest) GetTaskStatus() string {
	if x != nil {
		return x.TaskStatus
	}
	return ""
}

func (x *TaskQueueCompleteRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *TaskQueueCompleteRequest) GetContainerHostname() string {
	if x != nil {
		return x.ContainerHostname
	}
	return ""
}

func (x *TaskQueueCompleteRequest) GetKeepWarmSeconds() float32 {
	if x != nil {
		return x.KeepWarmSeconds
	}
	return 0
}

func (x *TaskQueueCompleteRequest) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type TaskQueueCompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskQueueCompleteResponse) Reset() {
	*x = TaskQueueCompleteResponse{}
	mi := &file_taskqueue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskQueueCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskQueueCompleteResponse) ProtoMessage() {}

func (x *TaskQueueCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskqueue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskQueueCompleteResponse.ProtoReflect.Descriptor instead.
func (*TaskQueueCompleteResponse) Descriptor() ([]byte, []int) {
	return file_taskqueue_proto_rawDescGZIP(), []int{7}
}

func (x *TaskQueueCompleteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TaskQueueCompleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TaskQueueMonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StubId        string                 `protobuf:"bytes,2,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskQueueMonitorRequest) Reset() {
	*x = TaskQueueMonitorRequest{}
	mi := &file_taskqueue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskQueueMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskQueueMonitorRequest) ProtoMessage() {}

func (x *TaskQueueMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskqueue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskQueueMonitorRequest.ProtoReflect.Descriptor instead.
func (*TaskQueueMonitorRequest) Descriptor() ([]byte, []int) {
	return file_taskqueue_proto_rawDescGZIP(), []int{8}
}

func (x *TaskQueueMonitorRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskQueueMonitorRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *TaskQueueMonitorRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type TaskQueueMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Cancelled     bool                   `protobuf:"varint,2,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	Complete      bool                   `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"`
	TimedOut      bool                   `protobuf:"varint,4,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskQueueMonitorResponse) Reset() {
	*x = TaskQueueMonitorResponse{}
	mi := &file_taskqueue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskQueueMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskQueueMonitorResponse) ProtoMessage() {}

func (x *TaskQueueMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskqueue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskQueueMonitorResponse.ProtoReflect.Descriptor instead.
func (*TaskQueueMonitorResponse) Descriptor() ([]byte, []int) {
	return file_taskqueue_proto_rawDescGZIP(), []int{9}
}

func (x *TaskQueueMonitorResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TaskQueueMonitorResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *TaskQueueMonitorResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *TaskQueueMonitorResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

type StartTaskQueueServeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StubId        string                 `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTaskQueueServeRequest) Reset() {
	*x = StartTaskQueueServeRequest{}
	mi := &file_taskqueue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskQueueServeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskQueueServeRequest) ProtoMessage() {}

func (x *StartTaskQueueServeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskqueue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskQueueServeRequest.ProtoReflect.Descriptor instead.
func (*StartTaskQueueServeRequest) Descriptor() ([]byte, []int) {
	return file_taskqueue_proto_rawDescGZIP(), []int{10}
}

func (x *StartTaskQueueServeRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *StartTaskQueueServeRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type StartTaskQueueServeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTaskQueueServeResponse) Reset() {
	*x = StartTaskQueueServeResponse{}
	mi := &file_taskqueue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskQueueServeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskQueueServeResponse) ProtoMessage() {}

func (x *StartTaskQueueServeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskqueue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskQueueServeResponse.ProtoReflect.Descriptor instead.
func (*StartTaskQueueServeResponse) Descriptor() ([]byte, []int) {
	return file_taskqueue_proto_rawDescGZIP(), []int{11}
}

func (x *StartTaskQueueServeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StartTaskQueueServeResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StartTaskQueueServeResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_taskqueue_proto protoreflect.FileDescriptor

const file_taskqueue_proto_rawDesc = "" +
	"\n" +
	"\x0ftaskqueue.proto\x12\ttaskqueue\"H\n" +
	"\x13TaskQueuePutRequest\x12\x17\n" +
	"\astub_id\x18\x01 \x01(\tR\x06stubId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"?\n" +
	"\x14TaskQueuePutResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"Q\n" +
	"\x13TaskQueuePopRequest\x12\x17\n" +
	"\astub_id\x18\x01 \x01(\tR\x06stubId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\"A\n" +
	"\x14TaskQueuePopResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x19\n" +
	"\btask_msg\x18\x02 \x01(\fR\ataskMsg\"1\n" +
	"\x16TaskQueueLengthRequest\x12\x17\n" +
	"\astub_id\x18\x01 \x01(\tR\x06stubId\"A\n" +
	"\x17TaskQueueLengthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x03R\x06length\"\xa8\x02\n" +
	"\x18TaskQueueCompleteRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\astub_id\x18\x02 \x01(\tR\x06stubId\x12#\n" +
	"\rtask_duration\x18\x03 \x01(\x02R\ftaskDuration\x12\x1f\n" +
	"\vtask_status\x18\x04 \x01(\tR\n" +
	"taskStatus\x12!\n" +
	"\fcontainer_id\x18\x05 \x01(\tR\vcontainerId\x12-\n" +
	"\x12container_hostname\x18\x06 \x01(\tR\x11containerHostname\x12*\n" +
	"\x11keep_warm_seconds\x18\a \x01(\x02R\x0fkeepWarmSeconds\x12\x16\n" +
	"\x06result\x18\b \x01(\fR\x06result\"E\n" +
	"\x19TaskQueueCompleteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"n\n" +
	"\x17TaskQueueMonitorRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\astub_id\x18\x02 \x01(\tR\x06stubId\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\"\x81\x01\n" +
	"\x18TaskQueueMonitorResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1c\n" +
	"\tcancelled\x18\x02 \x01(\bR\tcancelled\x12\x1a\n" +
	"\bcomplete\x18\x03 \x01(\bR\bcomplete\x12\x1b\n" +
	"\ttimed_out\x18\x04 \x01(\bR\btimedOut\"O\n" +
	"\x1aStartTaskQueueServeRequest\x12\x17\n" +
	"\astub_id\x18\x01 \x01(\tR\x06stubId\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\"m\n" +
	"\x1bStartTaskQueueServeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg2\xbd\x04\n" +
	"\x10TaskQueueService\x12Q\n" +
	"\fTaskQueuePut\x12\x1e.taskqueue.TaskQueuePutRequest\x1a\x1f.taskqueue.TaskQueuePutResponse\"\x00\x12Q\n" +
	"\fTaskQueuePop\x12\x1e.taskqueue.TaskQueuePopRequest\x1a\x1f.taskqueue.TaskQueuePopResponse\"\x00\x12]\n" +
	"\x10TaskQueueMonitor\x12\".taskqueue.TaskQueueMonitorRequest\x1a#.taskqueue.TaskQueueMonitorResponse0\x01\x12`\n" +
	"\x11TaskQueueComplete\x12#.taskqueue.TaskQueueCompleteRequest\x1a$.taskqueue.TaskQueueCompleteResponse\"\x00\x12Z\n" +
	"\x0fTaskQueueLength\x12!.taskqueue.TaskQueueLengthRequest\x1a\".taskqueue.TaskQueueLengthResponse\"\x00\x12f\n" +
	"\x13StartTaskQueueServe\x12%.taskqueue.StartTaskQueueServeRequest\x1a&.taskqueue.StartTaskQueueServeResponse\"\x00B#Z!github.com/beam-cloud/beta9/protob\x06proto3"

var (
	file_taskqueue_proto_rawDescOnce sync.Once
	file_taskqueue_proto_rawDescData []byte
)

func file_taskqueue_proto_rawDescGZIP() []byte {
	file_taskqueue_proto_rawDescOnce.Do(func() {
		file_taskqueue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taskqueue_proto_rawDesc), len(file_taskqueue_proto_rawDesc)))
	})
	return file_taskqueue_proto_rawDescData
}

var file_taskqueue_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_taskqueue_proto_goTypes = []any{
	(*TaskQueuePutRequest)(nil),         // 0: taskqueue.TaskQueuePutRequest
	(*TaskQueuePutResponse)(nil),        // 1: taskqueue.TaskQueuePutResponse
	(*TaskQueuePopRequest)(nil),         // 2: taskqueue.TaskQueuePopRequest
	(*TaskQueuePopResponse)(nil),        // 3: taskqueue.TaskQueuePopResponse
	(*TaskQueueLengthRequest)(nil),      // 4: taskqueue.TaskQueueLengthRequest
	(*TaskQueueLengthResponse)(nil),     // 5: taskqueue.TaskQueueLengthResponse
	(*TaskQueueCompleteRequest)(nil),    // 6: taskqueue.TaskQueueCompleteRequest
	(*TaskQueueCompleteResponse)(nil),   // 7: taskqueue.TaskQueueCompleteResponse
	(*TaskQueueMonitorRequest)(nil),     // 8: taskqueue.TaskQueueMonitorRequest
	(*TaskQueueMonitorResponse)(nil),    // 9: taskqueue.TaskQueueMonitorResponse
	(*StartTaskQueueServeRequest)(nil),  // 10: taskqueue.StartTaskQueueServeRequest
	(*StartTaskQueueServeResponse)(nil), // 11: taskqueue.StartTaskQueueServeResponse
}
var file_taskqueue_proto_depIdxs = []int32{
	0,  // 0: taskqueue.TaskQueueService.TaskQueuePut:input_type -> taskqueue.TaskQueuePutRequest
	2,  // 1: taskqueue.TaskQueueService.TaskQueuePop:input_type -> taskqueue.TaskQueuePopRequest
	8,  // 2: taskqueue.TaskQueueService.TaskQueueMonitor:input_type -> taskqueue.TaskQueueMonitorRequest
	6,  // 3: taskqueue.TaskQueueService.TaskQueueComplete:input_type -> taskqueue.TaskQueueCompleteRequest
	4,  // 4: taskqueue.TaskQueueService.TaskQueueLength:input_type -> taskqueue.TaskQueueLengthRequest
	10, // 5: taskqueue.TaskQueueService.StartTaskQueueServe:input_type -> taskqueue.StartTaskQueueServeRequest
	1,  // 6: taskqueue.TaskQueueService.TaskQueuePut:output_type -> taskqueue.TaskQueuePutResponse
	3,  // 7: taskqueue.TaskQueueService.TaskQueuePop:output_type -> taskqueue.TaskQueuePopResponse
	9,  // 8: taskqueue.TaskQueueService.TaskQueueMonitor:output_type -> taskqueue.TaskQueueMonitorResponse
	7,  // 9: taskqueue.TaskQueueService.TaskQueueComplete:output_type -> taskqueue.TaskQueueCompleteResponse
	5,  // 10: taskqueue.TaskQueueService.TaskQueueLength:output_type -> taskqueue.TaskQueueLengthResponse
	11, // 11: taskqueue.TaskQueueService.StartTaskQueueServe:output_type -> taskqueue.StartTaskQueueServeResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_taskqueue_proto_init() }
func file_taskqueue_proto_init() {
	if File_taskqueue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taskqueue_proto_rawDesc), len(file_taskqueue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taskqueue_proto_goTypes,
		DependencyIndexes: file_taskqueue_proto_depIdxs,
		MessageInfos:      file_taskqueue_proto_msgTypes,
	}.Build()
	File_taskqueue_proto = out.File
	file_taskqueue_proto_goTypes = nil
	file_taskqueue_proto_depIdxs = nil
}
