// Code generated by go2proto. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: types.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	WorkspaceId   uint32                 `protobuf:"varint,5,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *NullTime              `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *App) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *App) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *App) GetWorkspaceId() uint32 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *App) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *App) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *App) GetDeletedAt() *NullTime {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type BuildOptions struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceImage      string                 `protobuf:"bytes,1,opt,name=source_image,json=sourceImage,proto3" json:"source_image,omitempty"`
	Dockerfile       string                 `protobuf:"bytes,2,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`
	BuildCtxObject   string                 `protobuf:"bytes,3,opt,name=build_ctx_object,json=buildCtxObject,proto3" json:"build_ctx_object,omitempty"`
	SourceImageCreds string                 `protobuf:"bytes,4,opt,name=source_image_creds,json=sourceImageCreds,proto3" json:"source_image_creds,omitempty"`
	BuildSecrets     []string               `protobuf:"bytes,5,rep,name=build_secrets,json=buildSecrets,proto3" json:"build_secrets,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BuildOptions) Reset() {
	*x = BuildOptions{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildOptions) ProtoMessage() {}

func (x *BuildOptions) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildOptions.ProtoReflect.Descriptor instead.
func (*BuildOptions) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *BuildOptions) GetSourceImage() string {
	if x != nil {
		return x.SourceImage
	}
	return ""
}

func (x *BuildOptions) GetDockerfile() string {
	if x != nil {
		return x.Dockerfile
	}
	return ""
}

func (x *BuildOptions) GetBuildCtxObject() string {
	if x != nil {
		return x.BuildCtxObject
	}
	return ""
}

func (x *BuildOptions) GetSourceImageCreds() string {
	if x != nil {
		return x.SourceImageCreds
	}
	return ""
}

func (x *BuildOptions) GetBuildSecrets() []string {
	if x != nil {
		return x.BuildSecrets
	}
	return nil
}

type Checkpoint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId      string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	ExternalId        string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	SourceContainerId string                 `protobuf:"bytes,4,opt,name=source_container_id,json=sourceContainerId,proto3" json:"source_container_id,omitempty"`
	ContainerIp       string                 `protobuf:"bytes,5,opt,name=container_ip,json=containerIp,proto3" json:"container_ip,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	RemoteKey         string                 `protobuf:"bytes,7,opt,name=remote_key,json=remoteKey,proto3" json:"remote_key,omitempty"`
	StubType          string                 `protobuf:"bytes,10,opt,name=stub_type,json=stubType,proto3" json:"stub_type,omitempty"`
	ExposedPorts      []uint32               `protobuf:"varint,12,rep,packed,name=exposed_ports,json=exposedPorts,proto3" json:"exposed_ports,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastRestoredAt    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=last_restored_at,json=lastRestoredAt,proto3" json:"last_restored_at,omitempty"`
	DeletedAt         *NullTime              `protobuf:"bytes,15,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *Checkpoint) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *Checkpoint) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Checkpoint) GetSourceContainerId() string {
	if x != nil {
		return x.SourceContainerId
	}
	return ""
}

func (x *Checkpoint) GetContainerIp() string {
	if x != nil {
		return x.ContainerIp
	}
	return ""
}

func (x *Checkpoint) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Checkpoint) GetRemoteKey() string {
	if x != nil {
		return x.RemoteKey
	}
	return ""
}

func (x *Checkpoint) GetStubType() string {
	if x != nil {
		return x.StubType
	}
	return ""
}

func (x *Checkpoint) GetExposedPorts() []uint32 {
	if x != nil {
		return x.ExposedPorts
	}
	return nil
}

func (x *Checkpoint) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Checkpoint) GetLastRestoredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRestoredAt
	}
	return nil
}

func (x *Checkpoint) GetDeletedAt() *NullTime {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ConcurrencyLimit struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId        string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	WorkspaceId       uint32                 `protobuf:"varint,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	GpuLimit          uint32                 `protobuf:"varint,4,opt,name=gpu_limit,json=gpuLimit,proto3" json:"gpu_limit,omitempty"`
	CpuMillicoreLimit uint32                 `protobuf:"varint,5,opt,name=cpu_millicore_limit,json=cpuMillicoreLimit,proto3" json:"cpu_millicore_limit,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConcurrencyLimit) Reset() {
	*x = ConcurrencyLimit{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcurrencyLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcurrencyLimit) ProtoMessage() {}

func (x *ConcurrencyLimit) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcurrencyLimit.ProtoReflect.Descriptor instead.
func (*ConcurrencyLimit) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *ConcurrencyLimit) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConcurrencyLimit) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ConcurrencyLimit) GetWorkspaceId() uint32 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *ConcurrencyLimit) GetGpuLimit() uint32 {
	if x != nil {
		return x.GpuLimit
	}
	return 0
}

func (x *ConcurrencyLimit) GetCpuMillicoreLimit() uint32 {
	if x != nil {
		return x.CpuMillicoreLimit
	}
	return 0
}

func (x *ConcurrencyLimit) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConcurrencyLimit) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	StubId        string                 `protobuf:"bytes,2,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,6,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,7,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	MachineId     string                 `protobuf:"bytes,8,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,9,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *Container) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *Container) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *Container) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Container) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *Container) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Container) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Container) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Container) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *Container) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type ContainerRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ContainerId              string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	EntryPoint               []string               `protobuf:"bytes,2,rep,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	Env                      []string               `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	Cpu                      int64                  `protobuf:"varint,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory                   int64                  `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Gpu                      string                 `protobuf:"bytes,6,opt,name=gpu,proto3" json:"gpu,omitempty"`
	GpuRequest               []string               `protobuf:"bytes,7,rep,name=gpu_request,json=gpuRequest,proto3" json:"gpu_request,omitempty"`
	GpuCount                 uint32                 `protobuf:"varint,8,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	ImageId                  string                 `protobuf:"bytes,9,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	StubId                   string                 `protobuf:"bytes,10,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	WorkspaceId              string                 `protobuf:"bytes,11,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Workspace                *Workspace             `protobuf:"bytes,12,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Stub                     *StubWithRelated       `protobuf:"bytes,13,opt,name=stub,proto3" json:"stub,omitempty"`
	Timestamp                *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Mounts                   []*Mount               `protobuf:"bytes,15,rep,name=mounts,proto3" json:"mounts,omitempty"`
	RetryCount               int64                  `protobuf:"varint,16,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	PoolSelector             string                 `protobuf:"bytes,17,opt,name=pool_selector,json=poolSelector,proto3" json:"pool_selector,omitempty"`
	Preemptable              bool                   `protobuf:"varint,18,opt,name=preemptable,proto3" json:"preemptable,omitempty"`
	CheckpointEnabled        bool                   `protobuf:"varint,19,opt,name=checkpoint_enabled,json=checkpointEnabled,proto3" json:"checkpoint_enabled,omitempty"`
	BuildOptions             *BuildOptions          `protobuf:"bytes,20,opt,name=build_options,json=buildOptions,proto3" json:"build_options,omitempty"`
	Ports                    []uint32               `protobuf:"varint,21,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	CostPerMs                float64                `protobuf:"fixed64,22,opt,name=cost_per_ms,json=costPerMs,proto3" json:"cost_per_ms,omitempty"`
	AppId                    string                 `protobuf:"bytes,23,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Checkpoint               *Checkpoint            `protobuf:"bytes,24,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	ConfigPath               string                 `protobuf:"bytes,25,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	ImageCredentials         string                 `protobuf:"bytes,26,opt,name=image_credentials,json=imageCredentials,proto3" json:"image_credentials,omitempty"`
	BuildRegistryCredentials string                 `protobuf:"bytes,27,opt,name=build_registry_credentials,json=buildRegistryCredentials,proto3" json:"build_registry_credentials,omitempty"`
	BlockNetwork             bool                   `protobuf:"varint,28,opt,name=block_network,json=blockNetwork,proto3" json:"block_network,omitempty"`
	AllowList                []string               `protobuf:"bytes,29,rep,name=allow_list,json=allowList,proto3" json:"allow_list,omitempty"`
	DockerEnabled            bool                   `protobuf:"varint,30,opt,name=docker_enabled,json=dockerEnabled,proto3" json:"docker_enabled,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ContainerRequest) Reset() {
	*x = ContainerRequest{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRequest) ProtoMessage() {}

func (x *ContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerRequest.ProtoReflect.Descriptor instead.
func (*ContainerRequest) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerRequest) GetEntryPoint() []string {
	if x != nil {
		return x.EntryPoint
	}
	return nil
}

func (x *ContainerRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContainerRequest) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *ContainerRequest) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *ContainerRequest) GetGpu() string {
	if x != nil {
		return x.Gpu
	}
	return ""
}

func (x *ContainerRequest) GetGpuRequest() []string {
	if x != nil {
		return x.GpuRequest
	}
	return nil
}

func (x *ContainerRequest) GetGpuCount() uint32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *ContainerRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ContainerRequest) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *ContainerRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ContainerRequest) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *ContainerRequest) GetStub() *StubWithRelated {
	if x != nil {
		return x.Stub
	}
	return nil
}

func (x *ContainerRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ContainerRequest) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *ContainerRequest) GetRetryCount() int64 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *ContainerRequest) GetPoolSelector() string {
	if x != nil {
		return x.PoolSelector
	}
	return ""
}

func (x *ContainerRequest) GetPreemptable() bool {
	if x != nil {
		return x.Preemptable
	}
	return false
}

func (x *ContainerRequest) GetCheckpointEnabled() bool {
	if x != nil {
		return x.CheckpointEnabled
	}
	return false
}

func (x *ContainerRequest) GetBuildOptions() *BuildOptions {
	if x != nil {
		return x.BuildOptions
	}
	return nil
}

func (x *ContainerRequest) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerRequest) GetCostPerMs() float64 {
	if x != nil {
		return x.CostPerMs
	}
	return 0
}

func (x *ContainerRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ContainerRequest) GetCheckpoint() *Checkpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *ContainerRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *ContainerRequest) GetImageCredentials() string {
	if x != nil {
		return x.ImageCredentials
	}
	return ""
}

func (x *ContainerRequest) GetBuildRegistryCredentials() string {
	if x != nil {
		return x.BuildRegistryCredentials
	}
	return ""
}

func (x *ContainerRequest) GetBlockNetwork() bool {
	if x != nil {
		return x.BlockNetwork
	}
	return false
}

func (x *ContainerRequest) GetAllowList() []string {
	if x != nil {
		return x.AllowList
	}
	return nil
}

func (x *ContainerRequest) GetDockerEnabled() bool {
	if x != nil {
		return x.DockerEnabled
	}
	return false
}

type ContainerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	StubId        string                 `protobuf:"bytes,2,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ScheduledAt   int64                  `protobuf:"varint,4,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,5,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Gpu           string                 `protobuf:"bytes,6,opt,name=gpu,proto3" json:"gpu,omitempty"`
	GpuCount      uint32                 `protobuf:"varint,7,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	Cpu           int64                  `protobuf:"varint,8,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int64                  `protobuf:"varint,9,opt,name=memory,proto3" json:"memory,omitempty"`
	StartedAt     int64                  `protobuf:"varint,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerState) Reset() {
	*x = ContainerState{}
	mi := &file_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerState) ProtoMessage() {}

func (x *ContainerState) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerState.ProtoReflect.Descriptor instead.
func (*ContainerState) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerState) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerState) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *ContainerState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerState) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *ContainerState) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ContainerState) GetGpu() string {
	if x != nil {
		return x.Gpu
	}
	return ""
}

func (x *ContainerState) GetGpuCount() uint32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *ContainerState) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *ContainerState) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *ContainerState) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mode          int32                  `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTime       int64                  `protobuf:"varint,5,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	Owner         string                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Group         string                 `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`
	Path          string                 `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
	Permissions   uint32                 `protobuf:"varint,9,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileInfo) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *FileInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *FileInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetPermissions() uint32 {
	if x != nil {
		return x.Permissions
	}
	return 0
}

type FileSearchMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         *FileSearchRange       `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSearchMatch) Reset() {
	*x = FileSearchMatch{}
	mi := &file_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSearchMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSearchMatch) ProtoMessage() {}

func (x *FileSearchMatch) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSearchMatch.ProtoReflect.Descriptor instead.
func (*FileSearchMatch) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{8}
}

func (x *FileSearchMatch) GetRange() *FileSearchRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *FileSearchMatch) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type FileSearchPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          int32                  `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSearchPosition) Reset() {
	*x = FileSearchPosition{}
	mi := &file_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSearchPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSearchPosition) ProtoMessage() {}

func (x *FileSearchPosition) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSearchPosition.ProtoReflect.Descriptor instead.
func (*FileSearchPosition) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{9}
}

func (x *FileSearchPosition) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *FileSearchPosition) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type FileSearchRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *FileSearchPosition    `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *FileSearchPosition    `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSearchRange) Reset() {
	*x = FileSearchRange{}
	mi := &file_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSearchRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSearchRange) ProtoMessage() {}

func (x *FileSearchRange) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSearchRange.ProtoReflect.Descriptor instead.
func (*FileSearchRange) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{10}
}

func (x *FileSearchRange) GetStart() *FileSearchPosition {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *FileSearchRange) GetEnd() *FileSearchPosition {
	if x != nil {
		return x.End
	}
	return nil
}

type FileSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Matches       []*FileSearchMatch     `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSearchResult) Reset() {
	*x = FileSearchResult{}
	mi := &file_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSearchResult) ProtoMessage() {}

func (x *FileSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSearchResult.ProtoReflect.Descriptor instead.
func (*FileSearchResult) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{11}
}

func (x *FileSearchResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileSearchResult) GetMatches() []*FileSearchMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type Mount struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LocalPath        string                 `protobuf:"bytes,1,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	MountPath        string                 `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	LinkPath         string                 `protobuf:"bytes,3,opt,name=link_path,json=linkPath,proto3" json:"link_path,omitempty"`
	ReadOnly         bool                   `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	MountType        string                 `protobuf:"bytes,5,opt,name=mount_type,json=mountType,proto3" json:"mount_type,omitempty"`
	MountPointConfig *MountPointConfig      `protobuf:"bytes,6,opt,name=mount_point_config,json=mountPointConfig,proto3" json:"mount_point_config,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{12}
}

func (x *Mount) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *Mount) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *Mount) GetLinkPath() string {
	if x != nil {
		return x.LinkPath
	}
	return ""
}

func (x *Mount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Mount) GetMountType() string {
	if x != nil {
		return x.MountType
	}
	return ""
}

func (x *Mount) GetMountPointConfig() *MountPointConfig {
	if x != nil {
		return x.MountPointConfig
	}
	return nil
}

type MountPointConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BucketName     string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	AccessKey      string                 `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey      string                 `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	EndpointUrl    string                 `protobuf:"bytes,4,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	Region         string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	ReadOnly       bool                   `protobuf:"varint,6,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	ForcePathStyle bool                   `protobuf:"varint,7,opt,name=force_path_style,json=forcePathStyle,proto3" json:"force_path_style,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MountPointConfig) Reset() {
	*x = MountPointConfig{}
	mi := &file_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountPointConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountPointConfig) ProtoMessage() {}

func (x *MountPointConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountPointConfig.ProtoReflect.Descriptor instead.
func (*MountPointConfig) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{13}
}

func (x *MountPointConfig) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *MountPointConfig) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *MountPointConfig) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *MountPointConfig) GetEndpointUrl() string {
	if x != nil {
		return x.EndpointUrl
	}
	return ""
}

func (x *MountPointConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *MountPointConfig) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *MountPointConfig) GetForcePathStyle() bool {
	if x != nil {
		return x.ForcePathStyle
	}
	return false
}

type NullTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullTime) Reset() {
	*x = NullTime{}
	mi := &file_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullTime) ProtoMessage() {}

func (x *NullTime) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullTime.ProtoReflect.Descriptor instead.
func (*NullTime) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{14}
}

func (x *NullTime) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *NullTime) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type Object struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	WorkspaceId   uint32                 `protobuf:"varint,5,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{15}
}

func (x *Object) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Object) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Object) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Object) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Object) GetWorkspaceId() uint32 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *Object) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PricingPolicy struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MaxInFlight           int64                  `protobuf:"varint,1,opt,name=max_in_flight,json=maxInFlight,proto3" json:"max_in_flight,omitempty"`
	CostModel             string                 `protobuf:"bytes,2,opt,name=cost_model,json=costModel,proto3" json:"cost_model,omitempty"`
	CostPerTask           float64                `protobuf:"fixed64,3,opt,name=cost_per_task,json=costPerTask,proto3" json:"cost_per_task,omitempty"`
	CostPerTaskDurationMs float64                `protobuf:"fixed64,4,opt,name=cost_per_task_duration_ms,json=costPerTaskDurationMs,proto3" json:"cost_per_task_duration_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PricingPolicy) Reset() {
	*x = PricingPolicy{}
	mi := &file_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingPolicy) ProtoMessage() {}

func (x *PricingPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingPolicy.ProtoReflect.Descriptor instead.
func (*PricingPolicy) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{16}
}

func (x *PricingPolicy) GetMaxInFlight() int64 {
	if x != nil {
		return x.MaxInFlight
	}
	return 0
}

func (x *PricingPolicy) GetCostModel() string {
	if x != nil {
		return x.CostModel
	}
	return ""
}

func (x *PricingPolicy) GetCostPerTask() float64 {
	if x != nil {
		return x.CostPerTask
	}
	return 0
}

func (x *PricingPolicy) GetCostPerTaskDurationMs() float64 {
	if x != nil {
		return x.CostPerTaskDurationMs
	}
	return 0
}

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Cmd           string                 `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Cwd           string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Env           []string               `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty"`
	ExitCode      int32                  `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{17}
}

func (x *ProcessInfo) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *ProcessInfo) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ProcessInfo) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ProcessInfo) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type Stub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Config        string                 `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	ConfigVersion uint32                 `protobuf:"varint,6,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	ObjectId      uint32                 `protobuf:"varint,7,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	WorkspaceId   uint32                 `protobuf:"varint,8,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Public        bool                   `protobuf:"varint,11,opt,name=public,proto3" json:"public,omitempty"`
	AppId         uint32                 `protobuf:"varint,12,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stub) Reset() {
	*x = Stub{}
	mi := &file_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stub) ProtoMessage() {}

func (x *Stub) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stub.ProtoReflect.Descriptor instead.
func (*Stub) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{18}
}

func (x *Stub) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Stub) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Stub) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stub) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Stub) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Stub) GetConfigVersion() uint32 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *Stub) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *Stub) GetWorkspaceId() uint32 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *Stub) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Stub) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Stub) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *Stub) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type StubWithRelated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stub          *Stub                  `protobuf:"bytes,1,opt,name=stub,proto3" json:"stub,omitempty"`
	Workspace     *Workspace             `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Object        *Object                `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	App           *App                   `protobuf:"bytes,4,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StubWithRelated) Reset() {
	*x = StubWithRelated{}
	mi := &file_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StubWithRelated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StubWithRelated) ProtoMessage() {}

func (x *StubWithRelated) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StubWithRelated.ProtoReflect.Descriptor instead.
func (*StubWithRelated) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{19}
}

func (x *StubWithRelated) GetStub() *Stub {
	if x != nil {
		return x.Stub
	}
	return nil
}

func (x *StubWithRelated) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *StubWithRelated) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *StubWithRelated) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

type Worker struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TotalCpu             int64                  `protobuf:"varint,3,opt,name=total_cpu,json=totalCpu,proto3" json:"total_cpu,omitempty"`
	TotalMemory          int64                  `protobuf:"varint,4,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	TotalGpuCount        uint32                 `protobuf:"varint,5,opt,name=total_gpu_count,json=totalGpuCount,proto3" json:"total_gpu_count,omitempty"`
	FreeCpu              int64                  `protobuf:"varint,6,opt,name=free_cpu,json=freeCpu,proto3" json:"free_cpu,omitempty"`
	FreeMemory           int64                  `protobuf:"varint,7,opt,name=free_memory,json=freeMemory,proto3" json:"free_memory,omitempty"`
	FreeGpuCount         uint32                 `protobuf:"varint,8,opt,name=free_gpu_count,json=freeGpuCount,proto3" json:"free_gpu_count,omitempty"`
	Gpu                  string                 `protobuf:"bytes,9,opt,name=gpu,proto3" json:"gpu,omitempty"`
	PoolName             string                 `protobuf:"bytes,10,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	MachineId            string                 `protobuf:"bytes,11,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	ResourceVersion      int64                  `protobuf:"varint,12,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	RequiresPoolSelector bool                   `protobuf:"varint,13,opt,name=requires_pool_selector,json=requiresPoolSelector,proto3" json:"requires_pool_selector,omitempty"`
	Priority             int32                  `protobuf:"varint,14,opt,name=priority,proto3" json:"priority,omitempty"`
	Preemptable          bool                   `protobuf:"varint,15,opt,name=preemptable,proto3" json:"preemptable,omitempty"`
	BuildVersion         string                 `protobuf:"bytes,16,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	ActiveContainers     []*Container           `protobuf:"bytes,17,rep,name=active_containers,json=activeContainers,proto3" json:"active_containers,omitempty"`
	Runtime              string                 `protobuf:"bytes,18,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_types_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{20}
}

func (x *Worker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Worker) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Worker) GetTotalCpu() int64 {
	if x != nil {
		return x.TotalCpu
	}
	return 0
}

func (x *Worker) GetTotalMemory() int64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *Worker) GetTotalGpuCount() uint32 {
	if x != nil {
		return x.TotalGpuCount
	}
	return 0
}

func (x *Worker) GetFreeCpu() int64 {
	if x != nil {
		return x.FreeCpu
	}
	return 0
}

func (x *Worker) GetFreeMemory() int64 {
	if x != nil {
		return x.FreeMemory
	}
	return 0
}

func (x *Worker) GetFreeGpuCount() uint32 {
	if x != nil {
		return x.FreeGpuCount
	}
	return 0
}

func (x *Worker) GetGpu() string {
	if x != nil {
		return x.Gpu
	}
	return ""
}

func (x *Worker) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *Worker) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *Worker) GetResourceVersion() int64 {
	if x != nil {
		return x.ResourceVersion
	}
	return 0
}

func (x *Worker) GetRequiresPoolSelector() bool {
	if x != nil {
		return x.RequiresPoolSelector
	}
	return false
}

func (x *Worker) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Worker) GetPreemptable() bool {
	if x != nil {
		return x.Preemptable
	}
	return false
}

func (x *Worker) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

func (x *Worker) GetActiveContainers() []*Container {
	if x != nil {
		return x.ActiveContainers
	}
	return nil
}

func (x *Worker) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

type WorkerPoolState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SchedulingLatency  int64                  `protobuf:"varint,2,opt,name=scheduling_latency,json=schedulingLatency,proto3" json:"scheduling_latency,omitempty"`
	FreeGpu            uint32                 `protobuf:"varint,3,opt,name=free_gpu,json=freeGpu,proto3" json:"free_gpu,omitempty"`
	FreeCpu            int64                  `protobuf:"varint,4,opt,name=free_cpu,json=freeCpu,proto3" json:"free_cpu,omitempty"`
	FreeMemory         int64                  `protobuf:"varint,5,opt,name=free_memory,json=freeMemory,proto3" json:"free_memory,omitempty"`
	PendingWorkers     int64                  `protobuf:"varint,6,opt,name=pending_workers,json=pendingWorkers,proto3" json:"pending_workers,omitempty"`
	AvailableWorkers   int64                  `protobuf:"varint,7,opt,name=available_workers,json=availableWorkers,proto3" json:"available_workers,omitempty"`
	PendingContainers  int64                  `protobuf:"varint,8,opt,name=pending_containers,json=pendingContainers,proto3" json:"pending_containers,omitempty"`
	RunningContainers  int64                  `protobuf:"varint,9,opt,name=running_containers,json=runningContainers,proto3" json:"running_containers,omitempty"`
	RegisteredMachines int64                  `protobuf:"varint,10,opt,name=registered_machines,json=registeredMachines,proto3" json:"registered_machines,omitempty"`
	PendingMachines    int64                  `protobuf:"varint,11,opt,name=pending_machines,json=pendingMachines,proto3" json:"pending_machines,omitempty"`
	ReadyMachines      int64                  `protobuf:"varint,12,opt,name=ready_machines,json=readyMachines,proto3" json:"ready_machines,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkerPoolState) Reset() {
	*x = WorkerPoolState{}
	mi := &file_types_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerPoolState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerPoolState) ProtoMessage() {}

func (x *WorkerPoolState) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerPoolState.ProtoReflect.Descriptor instead.
func (*WorkerPoolState) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{21}
}

func (x *WorkerPoolState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkerPoolState) GetSchedulingLatency() int64 {
	if x != nil {
		return x.SchedulingLatency
	}
	return 0
}

func (x *WorkerPoolState) GetFreeGpu() uint32 {
	if x != nil {
		return x.FreeGpu
	}
	return 0
}

func (x *WorkerPoolState) GetFreeCpu() int64 {
	if x != nil {
		return x.FreeCpu
	}
	return 0
}

func (x *WorkerPoolState) GetFreeMemory() int64 {
	if x != nil {
		return x.FreeMemory
	}
	return 0
}

func (x *WorkerPoolState) GetPendingWorkers() int64 {
	if x != nil {
		return x.PendingWorkers
	}
	return 0
}

func (x *WorkerPoolState) GetAvailableWorkers() int64 {
	if x != nil {
		return x.AvailableWorkers
	}
	return 0
}

func (x *WorkerPoolState) GetPendingContainers() int64 {
	if x != nil {
		return x.PendingContainers
	}
	return 0
}

func (x *WorkerPoolState) GetRunningContainers() int64 {
	if x != nil {
		return x.RunningContainers
	}
	return 0
}

func (x *WorkerPoolState) GetRegisteredMachines() int64 {
	if x != nil {
		return x.RegisteredMachines
	}
	return 0
}

func (x *WorkerPoolState) GetPendingMachines() int64 {
	if x != nil {
		return x.PendingMachines
	}
	return 0
}

func (x *WorkerPoolState) GetReadyMachines() int64 {
	if x != nil {
		return x.ReadyMachines
	}
	return 0
}

type Workspace struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId         string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SigningKey         string                 `protobuf:"bytes,6,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
	VolumeCacheEnabled bool                   `protobuf:"varint,7,opt,name=volume_cache_enabled,json=volumeCacheEnabled,proto3" json:"volume_cache_enabled,omitempty"`
	MultiGpuEnabled    bool                   `protobuf:"varint,8,opt,name=multi_gpu_enabled,json=multiGpuEnabled,proto3" json:"multi_gpu_enabled,omitempty"`
	ConcurrencyLimitId uint32                 `protobuf:"varint,9,opt,name=concurrency_limit_id,json=concurrencyLimitId,proto3" json:"concurrency_limit_id,omitempty"`
	ConcurrencyLimit   *ConcurrencyLimit      `protobuf:"bytes,10,opt,name=concurrency_limit,json=concurrencyLimit,proto3" json:"concurrency_limit,omitempty"`
	StorageId          uint32                 `protobuf:"varint,11,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	Storage            *WorkspaceStorage      `protobuf:"bytes,12,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_types_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{22}
}

func (x *Workspace) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Workspace) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Workspace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workspace) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Workspace) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Workspace) GetSigningKey() string {
	if x != nil {
		return x.SigningKey
	}
	return ""
}

func (x *Workspace) GetVolumeCacheEnabled() bool {
	if x != nil {
		return x.VolumeCacheEnabled
	}
	return false
}

func (x *Workspace) GetMultiGpuEnabled() bool {
	if x != nil {
		return x.MultiGpuEnabled
	}
	return false
}

func (x *Workspace) GetConcurrencyLimitId() uint32 {
	if x != nil {
		return x.ConcurrencyLimitId
	}
	return 0
}

func (x *Workspace) GetConcurrencyLimit() *ConcurrencyLimit {
	if x != nil {
		return x.ConcurrencyLimit
	}
	return nil
}

func (x *Workspace) GetStorageId() uint32 {
	if x != nil {
		return x.StorageId
	}
	return 0
}

func (x *Workspace) GetStorage() *WorkspaceStorage {
	if x != nil {
		return x.Storage
	}
	return nil
}

type WorkspaceStorage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	BucketName    string                 `protobuf:"bytes,3,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	AccessKey     string                 `protobuf:"bytes,4,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,5,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	EndpointUrl   string                 `protobuf:"bytes,6,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	Region        string                 `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceStorage) Reset() {
	*x = WorkspaceStorage{}
	mi := &file_types_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceStorage) ProtoMessage() {}

func (x *WorkspaceStorage) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceStorage.ProtoReflect.Descriptor instead.
func (*WorkspaceStorage) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{23}
}

func (x *WorkspaceStorage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WorkspaceStorage) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *WorkspaceStorage) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *WorkspaceStorage) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *WorkspaceStorage) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *WorkspaceStorage) GetEndpointUrl() string {
	if x != nil {
		return x.EndpointUrl
	}
	return ""
}

func (x *WorkspaceStorage) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *WorkspaceStorage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkspaceStorage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\x05types\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x02\n" +
	"\x03App\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\fworkspace_id\x18\x05 \x01(\rR\vworkspaceId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12.\n" +
	"\n" +
	"deleted_at\x18\b \x01(\v2\x0f.types.NullTimeR\tdeletedAt\"\xce\x01\n" +
	"\fBuildOptions\x12!\n" +
	"\fsource_image\x18\x01 \x01(\tR\vsourceImage\x12\x1e\n" +
	"\n" +
	"dockerfile\x18\x02 \x01(\tR\n" +
	"dockerfile\x12(\n" +
	"\x10build_ctx_object\x18\x03 \x01(\tR\x0ebuildCtxObject\x12,\n" +
	"\x12source_image_creds\x18\x04 \x01(\tR\x10sourceImageCreds\x12#\n" +
	"\rbuild_secrets\x18\x05 \x03(\tR\fbuildSecrets\"\xcf\x03\n" +
	"\n" +
	"Checkpoint\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\x12.\n" +
	"\x13source_container_id\x18\x04 \x01(\tR\x11sourceContainerId\x12!\n" +
	"\fcontainer_ip\x18\x05 \x01(\tR\vcontainerIp\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"remote_key\x18\a \x01(\tR\tremoteKey\x12\x1b\n" +
	"\tstub_type\x18\n" +
	" \x01(\tR\bstubType\x12#\n" +
	"\rexposed_ports\x18\f \x03(\rR\fexposedPorts\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12D\n" +
	"\x10last_restored_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\x0elastRestoredAt\x12.\n" +
	"\n" +
	"deleted_at\x18\x0f \x01(\v2\x0f.types.NullTimeR\tdeletedAt\"\xa9\x02\n" +
	"\x10ConcurrencyLimit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\rR\vworkspaceId\x12\x1b\n" +
	"\tgpu_limit\x18\x04 \x01(\rR\bgpuLimit\x12.\n" +
	"\x13cpu_millicore_limit\x18\x05 \x01(\rR\x11cpuMillicoreLimit\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xdd\x02\n" +
	"\tContainer\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x17\n" +
	"\astub_id\x18\x02 \x01(\tR\x06stubId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12=\n" +
	"\fscheduled_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12!\n" +
	"\fworkspace_id\x18\x06 \x01(\tR\vworkspaceId\x12\x1b\n" +
	"\tworker_id\x18\a \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"machine_id\x18\b \x01(\tR\tmachineId\x12#\n" +
	"\rdeployment_id\x18\t \x01(\tR\fdeploymentId\"\xbd\b\n" +
	"\x10ContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1f\n" +
	"\ventry_point\x18\x02 \x03(\tR\n" +
	"entryPoint\x12\x10\n" +
	"\x03env\x18\x03 \x03(\tR\x03env\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\x03R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\x03R\x06memory\x12\x10\n" +
	"\x03gpu\x18\x06 \x01(\tR\x03gpu\x12\x1f\n" +
	"\vgpu_request\x18\a \x03(\tR\n" +
	"gpuRequest\x12\x1b\n" +
	"\tgpu_count\x18\b \x01(\rR\bgpuCount\x12\x19\n" +
	"\bimage_id\x18\t \x01(\tR\aimageId\x12\x17\n" +
	"\astub_id\x18\n" +
	" \x01(\tR\x06stubId\x12!\n" +
	"\fworkspace_id\x18\v \x01(\tR\vworkspaceId\x12.\n" +
	"\tworkspace\x18\f \x01(\v2\x10.types.WorkspaceR\tworkspace\x12*\n" +
	"\x04stub\x18\r \x01(\v2\x16.types.StubWithRelatedR\x04stub\x128\n" +
	"\ttimestamp\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12$\n" +
	"\x06mounts\x18\x0f \x03(\v2\f.types.MountR\x06mounts\x12\x1f\n" +
	"\vretry_count\x18\x10 \x01(\x03R\n" +
	"retryCount\x12#\n" +
	"\rpool_selector\x18\x11 \x01(\tR\fpoolSelector\x12 \n" +
	"\vpreemptable\x18\x12 \x01(\bR\vpreemptable\x12-\n" +
	"\x12checkpoint_enabled\x18\x13 \x01(\bR\x11checkpointEnabled\x128\n" +
	"\rbuild_options\x18\x14 \x01(\v2\x13.types.BuildOptionsR\fbuildOptions\x12\x14\n" +
	"\x05ports\x18\x15 \x03(\rR\x05ports\x12\x1e\n" +
	"\vcost_per_ms\x18\x16 \x01(\x01R\tcostPerMs\x12\x15\n" +
	"\x06app_id\x18\x17 \x01(\tR\x05appId\x121\n" +
	"\n" +
	"checkpoint\x18\x18 \x01(\v2\x11.types.CheckpointR\n" +
	"checkpoint\x12\x1f\n" +
	"\vconfig_path\x18\x19 \x01(\tR\n" +
	"configPath\x12+\n" +
	"\x11image_credentials\x18\x1a \x01(\tR\x10imageCredentials\x12<\n" +
	"\x1abuild_registry_credentials\x18\x1b \x01(\tR\x18buildRegistryCredentials\x12#\n" +
	"\rblock_network\x18\x1c \x01(\bR\fblockNetwork\x12\x1d\n" +
	"\n" +
	"allow_list\x18\x1d \x03(\tR\tallowList\x12%\n" +
	"\x0edocker_enabled\x18\x1e \x01(\bR\rdockerEnabled\"\xa2\x02\n" +
	"\x0eContainerState\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x17\n" +
	"\astub_id\x18\x02 \x01(\tR\x06stubId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fscheduled_at\x18\x04 \x01(\x03R\vscheduledAt\x12!\n" +
	"\fworkspace_id\x18\x05 \x01(\tR\vworkspaceId\x12\x10\n" +
	"\x03gpu\x18\x06 \x01(\tR\x03gpu\x12\x1b\n" +
	"\tgpu_count\x18\a \x01(\rR\bgpuCount\x12\x10\n" +
	"\x03cpu\x18\b \x01(\x03R\x03cpu\x12\x16\n" +
	"\x06memory\x18\t \x01(\x03R\x06memory\x12\x1d\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\x03R\tstartedAt\"\xda\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\x05R\x04mode\x12\x19\n" +
	"\bmod_time\x18\x05 \x01(\x03R\amodTime\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12\x14\n" +
	"\x05group\x18\a \x01(\tR\x05group\x12\x12\n" +
	"\x04path\x18\b \x01(\tR\x04path\x12 \n" +
	"\vpermissions\x18\t \x01(\rR\vpermissions\"Y\n" +
	"\x0fFileSearchMatch\x12,\n" +
	"\x05range\x18\x01 \x01(\v2\x16.types.FileSearchRangeR\x05range\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"@\n" +
	"\x12FileSearchPosition\x12\x12\n" +
	"\x04line\x18\x01 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x02 \x01(\x05R\x06column\"o\n" +
	"\x0fFileSearchRange\x12/\n" +
	"\x05start\x18\x01 \x01(\v2\x19.types.FileSearchPositionR\x05start\x12+\n" +
	"\x03end\x18\x02 \x01(\v2\x19.types.FileSearchPositionR\x03end\"X\n" +
	"\x10FileSearchResult\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x120\n" +
	"\amatches\x18\x02 \x03(\v2\x16.types.FileSearchMatchR\amatches\"\xe5\x01\n" +
	"\x05Mount\x12\x1d\n" +
	"\n" +
	"local_path\x18\x01 \x01(\tR\tlocalPath\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\x12\x1b\n" +
	"\tlink_path\x18\x03 \x01(\tR\blinkPath\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\x12\x1d\n" +
	"\n" +
	"mount_type\x18\x05 \x01(\tR\tmountType\x12E\n" +
	"\x12mount_point_config\x18\x06 \x01(\v2\x17.types.MountPointConfigR\x10mountPointConfig\"\xf3\x01\n" +
	"\x10MountPointConfig\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12\x1d\n" +
	"\n" +
	"access_key\x18\x02 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x03 \x01(\tR\tsecretKey\x12!\n" +
	"\fendpoint_url\x18\x04 \x01(\tR\vendpointUrl\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x1b\n" +
	"\tread_only\x18\x06 \x01(\bR\breadOnly\x12(\n" +
	"\x10force_path_style\x18\a \x01(\bR\x0eforcePathStyle\"P\n" +
	"\bNullTime\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\"\xbf\x01\n" +
	"\x06Object\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12!\n" +
	"\fworkspace_id\x18\x05 \x01(\rR\vworkspaceId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb0\x01\n" +
	"\rPricingPolicy\x12\"\n" +
	"\rmax_in_flight\x18\x01 \x01(\x03R\vmaxInFlight\x12\x1d\n" +
	"\n" +
	"cost_model\x18\x02 \x01(\tR\tcostModel\x12\"\n" +
	"\rcost_per_task\x18\x03 \x01(\x01R\vcostPerTask\x128\n" +
	"\x19cost_per_task_duration_ms\x18\x04 \x01(\x01R\x15costPerTaskDurationMs\"\x8c\x01\n" +
	"\vProcessInfo\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x10\n" +
	"\x03cmd\x18\x03 \x01(\tR\x03cmd\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12\x10\n" +
	"\x03env\x18\x05 \x03(\tR\x03env\x12\x1b\n" +
	"\texit_code\x18\x06 \x01(\x05R\bexitCode\"\x83\x03\n" +
	"\x04Stub\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06config\x18\x05 \x01(\tR\x06config\x12%\n" +
	"\x0econfig_version\x18\x06 \x01(\rR\rconfigVersion\x12\x1b\n" +
	"\tobject_id\x18\a \x01(\rR\bobjectId\x12!\n" +
	"\fworkspace_id\x18\b \x01(\rR\vworkspaceId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x16\n" +
	"\x06public\x18\v \x01(\bR\x06public\x12\x15\n" +
	"\x06app_id\x18\f \x01(\rR\x05appId\"\xa7\x01\n" +
	"\x0fStubWithRelated\x12\x1f\n" +
	"\x04stub\x18\x01 \x01(\v2\v.types.StubR\x04stub\x12.\n" +
	"\tworkspace\x18\x02 \x01(\v2\x10.types.WorkspaceR\tworkspace\x12%\n" +
	"\x06object\x18\x03 \x01(\v2\r.types.ObjectR\x06object\x12\x1c\n" +
	"\x03app\x18\x04 \x01(\v2\n" +
	".types.AppR\x03app\"\xe5\x04\n" +
	"\x06Worker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\ttotal_cpu\x18\x03 \x01(\x03R\btotalCpu\x12!\n" +
	"\ftotal_memory\x18\x04 \x01(\x03R\vtotalMemory\x12&\n" +
	"\x0ftotal_gpu_count\x18\x05 \x01(\rR\rtotalGpuCount\x12\x19\n" +
	"\bfree_cpu\x18\x06 \x01(\x03R\afreeCpu\x12\x1f\n" +
	"\vfree_memory\x18\a \x01(\x03R\n" +
	"freeMemory\x12$\n" +
	"\x0efree_gpu_count\x18\b \x01(\rR\ffreeGpuCount\x12\x10\n" +
	"\x03gpu\x18\t \x01(\tR\x03gpu\x12\x1b\n" +
	"\tpool_name\x18\n" +
	" \x01(\tR\bpoolName\x12\x1d\n" +
	"\n" +
	"machine_id\x18\v \x01(\tR\tmachineId\x12)\n" +
	"\x10resource_version\x18\f \x01(\x03R\x0fresourceVersion\x124\n" +
	"\x16requires_pool_selector\x18\r \x01(\bR\x14requiresPoolSelector\x12\x1a\n" +
	"\bpriority\x18\x0e \x01(\x05R\bpriority\x12 \n" +
	"\vpreemptable\x18\x0f \x01(\bR\vpreemptable\x12#\n" +
	"\rbuild_version\x18\x10 \x01(\tR\fbuildVersion\x12=\n" +
	"\x11active_containers\x18\x11 \x03(\v2\x10.types.ContainerR\x10activeContainers\x12\x18\n" +
	"\aruntime\x18\x12 \x01(\tR\aruntime\"\xe6\x03\n" +
	"\x0fWorkerPoolState\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12-\n" +
	"\x12scheduling_latency\x18\x02 \x01(\x03R\x11schedulingLatency\x12\x19\n" +
	"\bfree_gpu\x18\x03 \x01(\rR\afreeGpu\x12\x19\n" +
	"\bfree_cpu\x18\x04 \x01(\x03R\afreeCpu\x12\x1f\n" +
	"\vfree_memory\x18\x05 \x01(\x03R\n" +
	"freeMemory\x12'\n" +
	"\x0fpending_workers\x18\x06 \x01(\x03R\x0ependingWorkers\x12+\n" +
	"\x11available_workers\x18\a \x01(\x03R\x10availableWorkers\x12-\n" +
	"\x12pending_containers\x18\b \x01(\x03R\x11pendingContainers\x12-\n" +
	"\x12running_containers\x18\t \x01(\x03R\x11runningContainers\x12/\n" +
	"\x13registered_machines\x18\n" +
	" \x01(\x03R\x12registeredMachines\x12)\n" +
	"\x10pending_machines\x18\v \x01(\x03R\x0fpendingMachines\x12%\n" +
	"\x0eready_machines\x18\f \x01(\x03R\rreadyMachines\"\x8f\x04\n" +
	"\tWorkspace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsigning_key\x18\x06 \x01(\tR\n" +
	"signingKey\x120\n" +
	"\x14volume_cache_enabled\x18\a \x01(\bR\x12volumeCacheEnabled\x12*\n" +
	"\x11multi_gpu_enabled\x18\b \x01(\bR\x0fmultiGpuEnabled\x120\n" +
	"\x14concurrency_limit_id\x18\t \x01(\rR\x12concurrencyLimitId\x12D\n" +
	"\x11concurrency_limit\x18\n" +
	" \x01(\v2\x17.types.ConcurrencyLimitR\x10concurrencyLimit\x12\x1d\n" +
	"\n" +
	"storage_id\x18\v \x01(\rR\tstorageId\x121\n" +
	"\astorage\x18\f \x01(\v2\x17.types.WorkspaceStorageR\astorage\"\xd3\x02\n" +
	"\x10WorkspaceStorage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x1f\n" +
	"\vbucket_name\x18\x03 \x01(\tR\n" +
	"bucketName\x12\x1d\n" +
	"\n" +
	"access_key\x18\x04 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x05 \x01(\tR\tsecretKey\x12!\n" +
	"\fendpoint_url\x18\x06 \x01(\tR\vendpointUrl\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB#Z!github.com/beam-cloud/beta9/protob\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_types_proto_goTypes = []any{
	(*App)(nil),                   // 0: types.App
	(*BuildOptions)(nil),          // 1: types.BuildOptions
	(*Checkpoint)(nil),            // 2: types.Checkpoint
	(*ConcurrencyLimit)(nil),      // 3: types.ConcurrencyLimit
	(*Container)(nil),             // 4: types.Container
	(*ContainerRequest)(nil),      // 5: types.ContainerRequest
	(*ContainerState)(nil),        // 6: types.ContainerState
	(*FileInfo)(nil),              // 7: types.FileInfo
	(*FileSearchMatch)(nil),       // 8: types.FileSearchMatch
	(*FileSearchPosition)(nil),    // 9: types.FileSearchPosition
	(*FileSearchRange)(nil),       // 10: types.FileSearchRange
	(*FileSearchResult)(nil),      // 11: types.FileSearchResult
	(*Mount)(nil),                 // 12: types.Mount
	(*MountPointConfig)(nil),      // 13: types.MountPointConfig
	(*NullTime)(nil),              // 14: types.NullTime
	(*Object)(nil),                // 15: types.Object
	(*PricingPolicy)(nil),         // 16: types.PricingPolicy
	(*ProcessInfo)(nil),           // 17: types.ProcessInfo
	(*Stub)(nil),                  // 18: types.Stub
	(*StubWithRelated)(nil),       // 19: types.StubWithRelated
	(*Worker)(nil),                // 20: types.Worker
	(*WorkerPoolState)(nil),       // 21: types.WorkerPoolState
	(*Workspace)(nil),             // 22: types.Workspace
	(*WorkspaceStorage)(nil),      // 23: types.WorkspaceStorage
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
}
var file_types_proto_depIdxs = []int32{
	24, // 0: types.App.created_at:type_name -> google.protobuf.Timestamp
	24, // 1: types.App.updated_at:type_name -> google.protobuf.Timestamp
	14, // 2: types.App.deleted_at:type_name -> types.NullTime
	24, // 3: types.Checkpoint.created_at:type_name -> google.protobuf.Timestamp
	24, // 4: types.Checkpoint.last_restored_at:type_name -> google.protobuf.Timestamp
	14, // 5: types.Checkpoint.deleted_at:type_name -> types.NullTime
	24, // 6: types.ConcurrencyLimit.created_at:type_name -> google.protobuf.Timestamp
	24, // 7: types.ConcurrencyLimit.updated_at:type_name -> google.protobuf.Timestamp
	24, // 8: types.Container.scheduled_at:type_name -> google.protobuf.Timestamp
	24, // 9: types.Container.started_at:type_name -> google.protobuf.Timestamp
	22, // 10: types.ContainerRequest.workspace:type_name -> types.Workspace
	19, // 11: types.ContainerRequest.stub:type_name -> types.StubWithRelated
	24, // 12: types.ContainerRequest.timestamp:type_name -> google.protobuf.Timestamp
	12, // 13: types.ContainerRequest.mounts:type_name -> types.Mount
	1,  // 14: types.ContainerRequest.build_options:type_name -> types.BuildOptions
	2,  // 15: types.ContainerRequest.checkpoint:type_name -> types.Checkpoint
	10, // 16: types.FileSearchMatch.range:type_name -> types.FileSearchRange
	9,  // 17: types.FileSearchRange.start:type_name -> types.FileSearchPosition
	9,  // 18: types.FileSearchRange.end:type_name -> types.FileSearchPosition
	8,  // 19: types.FileSearchResult.matches:type_name -> types.FileSearchMatch
	13, // 20: types.Mount.mount_point_config:type_name -> types.MountPointConfig
	24, // 21: types.NullTime.time:type_name -> google.protobuf.Timestamp
	24, // 22: types.Object.created_at:type_name -> google.protobuf.Timestamp
	24, // 23: types.Stub.created_at:type_name -> google.protobuf.Timestamp
	24, // 24: types.Stub.updated_at:type_name -> google.protobuf.Timestamp
	18, // 25: types.StubWithRelated.stub:type_name -> types.Stub
	22, // 26: types.StubWithRelated.workspace:type_name -> types.Workspace
	15, // 27: types.StubWithRelated.object:type_name -> types.Object
	0,  // 28: types.StubWithRelated.app:type_name -> types.App
	4,  // 29: types.Worker.active_containers:type_name -> types.Container
	24, // 30: types.Workspace.created_at:type_name -> google.protobuf.Timestamp
	24, // 31: types.Workspace.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 32: types.Workspace.concurrency_limit:type_name -> types.ConcurrencyLimit
	23, // 33: types.Workspace.storage:type_name -> types.WorkspaceStorage
	24, // 34: types.WorkspaceStorage.created_at:type_name -> google.protobuf.Timestamp
	24, // 35: types.WorkspaceStorage.updated_at:type_name -> google.protobuf.Timestamp
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
