// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: worker_repo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNextContainerRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextContainerRequestRequest) Reset() {
	*x = GetNextContainerRequestRequest{}
	mi := &file_worker_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextContainerRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextContainerRequestRequest) ProtoMessage() {}

func (x *GetNextContainerRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextContainerRequestRequest.ProtoReflect.Descriptor instead.
func (*GetNextContainerRequestRequest) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{0}
}

func (x *GetNextContainerRequestRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type GetNextContainerRequestResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ok               bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ContainerRequest *ContainerRequest      `protobuf:"bytes,2,opt,name=container_request,json=containerRequest,proto3" json:"container_request,omitempty"`
	ErrorMsg         string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetNextContainerRequestResponse) Reset() {
	*x = GetNextContainerRequestResponse{}
	mi := &file_worker_repo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextContainerRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextContainerRequestResponse) ProtoMessage() {}

func (x *GetNextContainerRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextContainerRequestResponse.ProtoReflect.Descriptor instead.
func (*GetNextContainerRequestResponse) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{1}
}

func (x *GetNextContainerRequestResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetNextContainerRequestResponse) GetContainerRequest() *ContainerRequest {
	if x != nil {
		return x.ContainerRequest
	}
	return nil
}

func (x *GetNextContainerRequestResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SetImagePullLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ImageId       string                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetImagePullLockRequest) Reset() {
	*x = SetImagePullLockRequest{}
	mi := &file_worker_repo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetImagePullLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetImagePullLockRequest) ProtoMessage() {}

func (x *SetImagePullLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetImagePullLockRequest.ProtoReflect.Descriptor instead.
func (*SetImagePullLockRequest) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{2}
}

func (x *SetImagePullLockRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *SetImagePullLockRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type SetImagePullLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetImagePullLockResponse) Reset() {
	*x = SetImagePullLockResponse{}
	mi := &file_worker_repo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetImagePullLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetImagePullLockResponse) ProtoMessage() {}

func (x *SetImagePullLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetImagePullLockResponse.ProtoReflect.Descriptor instead.
func (*SetImagePullLockResponse) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{3}
}

func (x *SetImagePullLockResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SetImagePullLockResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SetImagePullLockResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type RemoveImagePullLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ImageId       string                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImagePullLockRequest) Reset() {
	*x = RemoveImagePullLockRequest{}
	mi := &file_worker_repo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImagePullLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImagePullLockRequest) ProtoMessage() {}

func (x *RemoveImagePullLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImagePullLockRequest.ProtoReflect.Descriptor instead.
func (*RemoveImagePullLockRequest) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveImagePullLockRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RemoveImagePullLockRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *RemoveImagePullLockRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RemoveImagePullLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImagePullLockResponse) Reset() {
	*x = RemoveImagePullLockResponse{}
	mi := &file_worker_repo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImagePullLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImagePullLockResponse) ProtoMessage() {}

func (x *RemoveImagePullLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImagePullLockResponse.ProtoReflect.Descriptor instead.
func (*RemoveImagePullLockResponse) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveImagePullLockResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RemoveImagePullLockResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type AddContainerToWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	PoolName      string                 `protobuf:"bytes,3,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	PodHostname   string                 `protobuf:"bytes,4,opt,name=pod_hostname,json=podHostname,proto3" json:"pod_hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddContainerToWorkerRequest) Reset() {
	*x = AddContainerToWorkerRequest{}
	mi := &file_worker_repo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddContainerToWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContainerToWorkerRequest) ProtoMessage() {}

func (x *AddContainerToWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContainerToWorkerRequest.ProtoReflect.Descriptor instead.
func (*AddContainerToWorkerRequest) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{6}
}

func (x *AddContainerToWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *AddContainerToWorkerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *AddContainerToWorkerRequest) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *AddContainerToWorkerRequest) GetPodHostname() string {
	if x != nil {
		return x.PodHostname
	}
	return ""
}

type AddContainerToWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddContainerToWorkerResponse) Reset() {
	*x = AddContainerToWorkerResponse{}
	mi := &file_worker_repo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddContainerToWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContainerToWorkerResponse) ProtoMessage() {}

func (x *AddContainerToWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContainerToWorkerResponse.ProtoReflect.Descriptor instead.
func (*AddContainerToWorkerResponse) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{7}
}

func (x *AddContainerToWorkerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AddContainerToWorkerResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type RemoveContainerFromWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	PoolName      string                 `protobuf:"bytes,3,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	PodHostname   string                 `protobuf:"bytes,4,opt,name=pod_hostname,json=podHostname,proto3" json:"pod_hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContainerFromWorkerRequest) Reset() {
	*x = RemoveContainerFromWorkerRequest{}
	mi := &file_worker_repo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContainerFromWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContainerFromWorkerRequest) ProtoMessage() {}

func (x *RemoveContainerFromWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContainerFromWorkerRequest.ProtoReflect.Descriptor instead.
func (*RemoveContainerFromWorkerRequest) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveContainerFromWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RemoveContainerFromWorkerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RemoveContainerFromWorkerRequest) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *RemoveContainerFromWorkerRequest) GetPodHostname() string {
	if x != nil {
		return x.PodHostname
	}
	return ""
}

type RemoveContainerFromWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContainerFromWorkerResponse) Reset() {
	*x = RemoveContainerFromWorkerResponse{}
	mi := &file_worker_repo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContainerFromWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContainerFromWorkerResponse) ProtoMessage() {}

func (x *RemoveContainerFromWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContainerFromWorkerResponse.ProtoReflect.Descriptor instead.
func (*RemoveContainerFromWorkerResponse) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveContainerFromWorkerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RemoveContainerFromWorkerResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GetWorkerByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkerByIdRequest) Reset() {
	*x = GetWorkerByIdRequest{}
	mi := &file_worker_repo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkerByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerByIdRequest) ProtoMessage() {}

func (x *GetWorkerByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerByIdRequest.ProtoReflect.Descriptor instead.
func (*GetWorkerByIdRequest) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{10}
}

func (x *GetWorkerByIdRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type GetWorkerByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Worker        *Worker                `protobuf:"bytes,2,opt,name=worker,proto3" json:"worker,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkerByIdResponse) Reset() {
	*x = GetWorkerByIdResponse{}
	mi := &file_worker_repo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkerByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerByIdResponse) ProtoMessage() {}

func (x *GetWorkerByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerByIdResponse.ProtoReflect.Descriptor instead.
func (*GetWorkerByIdResponse) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{11}
}

func (x *GetWorkerByIdResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetWorkerByIdResponse) GetWorker() *Worker {
	if x != nil {
		return x.Worker
	}
	return nil
}

func (x *GetWorkerByIdResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ToggleWorkerAvailableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleWorkerAvailableRequest) Reset() {
	*x = ToggleWorkerAvailableRequest{}
	mi := &file_worker_repo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleWorkerAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleWorkerAvailableRequest) ProtoMessage() {}

func (x *ToggleWorkerAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleWorkerAvailableRequest.ProtoReflect.Descriptor instead.
func (*ToggleWorkerAvailableRequest) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{12}
}

func (x *ToggleWorkerAvailableRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type ToggleWorkerAvailableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleWorkerAvailableResponse) Reset() {
	*x = ToggleWorkerAvailableResponse{}
	mi := &file_worker_repo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleWorkerAvailableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleWorkerAvailableResponse) ProtoMessage() {}

func (x *ToggleWorkerAvailableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleWorkerAvailableResponse.ProtoReflect.Descriptor instead.
func (*ToggleWorkerAvailableResponse) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{13}
}

func (x *ToggleWorkerAvailableResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ToggleWorkerAvailableResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type RemoveWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWorkerRequest) Reset() {
	*x = RemoveWorkerRequest{}
	mi := &file_worker_repo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWorkerRequest) ProtoMessage() {}

func (x *RemoveWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWorkerRequest.ProtoReflect.Descriptor instead.
func (*RemoveWorkerRequest) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type RemoveWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWorkerResponse) Reset() {
	*x = RemoveWorkerResponse{}
	mi := &file_worker_repo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWorkerResponse) ProtoMessage() {}

func (x *RemoveWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWorkerResponse.ProtoReflect.Descriptor instead.
func (*RemoveWorkerResponse) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveWorkerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RemoveWorkerResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type UpdateWorkerCapacityRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkerId         string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CapacityChange   int64                  `protobuf:"varint,2,opt,name=capacity_change,json=capacityChange,proto3" json:"capacity_change,omitempty"`
	ContainerRequest *ContainerRequest      `protobuf:"bytes,3,opt,name=container_request,json=containerRequest,proto3" json:"container_request,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateWorkerCapacityRequest) Reset() {
	*x = UpdateWorkerCapacityRequest{}
	mi := &file_worker_repo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkerCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkerCapacityRequest) ProtoMessage() {}

func (x *UpdateWorkerCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkerCapacityRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkerCapacityRequest) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateWorkerCapacityRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *UpdateWorkerCapacityRequest) GetCapacityChange() int64 {
	if x != nil {
		return x.CapacityChange
	}
	return 0
}

func (x *UpdateWorkerCapacityRequest) GetContainerRequest() *ContainerRequest {
	if x != nil {
		return x.ContainerRequest
	}
	return nil
}

type UpdateWorkerCapacityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkerCapacityResponse) Reset() {
	*x = UpdateWorkerCapacityResponse{}
	mi := &file_worker_repo_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkerCapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkerCapacityResponse) ProtoMessage() {}

func (x *UpdateWorkerCapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkerCapacityResponse.ProtoReflect.Descriptor instead.
func (*UpdateWorkerCapacityResponse) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateWorkerCapacityResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UpdateWorkerCapacityResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SetWorkerKeepAliveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWorkerKeepAliveRequest) Reset() {
	*x = SetWorkerKeepAliveRequest{}
	mi := &file_worker_repo_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWorkerKeepAliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWorkerKeepAliveRequest) ProtoMessage() {}

func (x *SetWorkerKeepAliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWorkerKeepAliveRequest.ProtoReflect.Descriptor instead.
func (*SetWorkerKeepAliveRequest) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{18}
}

func (x *SetWorkerKeepAliveRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type SetWorkerKeepAliveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWorkerKeepAliveResponse) Reset() {
	*x = SetWorkerKeepAliveResponse{}
	mi := &file_worker_repo_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWorkerKeepAliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWorkerKeepAliveResponse) ProtoMessage() {}

func (x *SetWorkerKeepAliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWorkerKeepAliveResponse.ProtoReflect.Descriptor instead.
func (*SetWorkerKeepAliveResponse) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{19}
}

func (x *SetWorkerKeepAliveResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SetWorkerKeepAliveResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SetNetworkLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkPrefix string                 `protobuf:"bytes,1,opt,name=network_prefix,json=networkPrefix,proto3" json:"network_prefix,omitempty"`
	Ttl           int32                  `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Retries       int32                  `protobuf:"varint,3,opt,name=retries,proto3" json:"retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNetworkLockRequest) Reset() {
	*x = SetNetworkLockRequest{}
	mi := &file_worker_repo_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNetworkLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNetworkLockRequest) ProtoMessage() {}

func (x *SetNetworkLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNetworkLockRequest.ProtoReflect.Descriptor instead.
func (*SetNetworkLockRequest) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{20}
}

func (x *SetNetworkLockRequest) GetNetworkPrefix() string {
	if x != nil {
		return x.NetworkPrefix
	}
	return ""
}

func (x *SetNetworkLockRequest) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *SetNetworkLockRequest) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

type SetNetworkLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNetworkLockResponse) Reset() {
	*x = SetNetworkLockResponse{}
	mi := &file_worker_repo_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNetworkLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNetworkLockResponse) ProtoMessage() {}

func (x *SetNetworkLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNetworkLockResponse.ProtoReflect.Descriptor instead.
func (*SetNetworkLockResponse) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{21}
}

func (x *SetNetworkLockResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SetNetworkLockResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SetNetworkLockResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type RemoveNetworkLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkPrefix string                 `protobuf:"bytes,1,opt,name=network_prefix,json=networkPrefix,proto3" json:"network_prefix,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNetworkLockRequest) Reset() {
	*x = RemoveNetworkLockRequest{}
	mi := &file_worker_repo_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNetworkLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNetworkLockRequest) ProtoMessage() {}

func (x *RemoveNetworkLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNetworkLockRequest.ProtoReflect.Descriptor instead.
func (*RemoveNetworkLockRequest) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveNetworkLockRequest) GetNetworkPrefix() string {
	if x != nil {
		return x.NetworkPrefix
	}
	return ""
}

func (x *RemoveNetworkLockRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RemoveNetworkLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNetworkLockResponse) Reset() {
	*x = RemoveNetworkLockResponse{}
	mi := &file_worker_repo_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNetworkLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNetworkLockResponse) ProtoMessage() {}

func (x *RemoveNetworkLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNetworkLockResponse.ProtoReflect.Descriptor instead.
func (*RemoveNetworkLockResponse) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveNetworkLockResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RemoveNetworkLockResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SetContainerIpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkPrefix string                 `protobuf:"bytes,1,opt,name=network_prefix,json=networkPrefix,proto3" json:"network_prefix,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetContainerIpRequest) Reset() {
	*x = SetContainerIpRequest{}
	mi := &file_worker_repo_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetContainerIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetContainerIpRequest) ProtoMessage() {}

func (x *SetContainerIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetContainerIpRequest.ProtoReflect.Descriptor instead.
func (*SetContainerIpRequest) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{24}
}

func (x *SetContainerIpRequest) GetNetworkPrefix() string {
	if x != nil {
		return x.NetworkPrefix
	}
	return ""
}

func (x *SetContainerIpRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *SetContainerIpRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type SetContainerIpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetContainerIpResponse) Reset() {
	*x = SetContainerIpResponse{}
	mi := &file_worker_repo_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetContainerIpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetContainerIpResponse) ProtoMessage() {}

func (x *SetContainerIpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetContainerIpResponse.ProtoReflect.Descriptor instead.
func (*SetContainerIpResponse) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{25}
}

func (x *SetContainerIpResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SetContainerIpResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GetContainerIpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkPrefix string                 `protobuf:"bytes,1,opt,name=network_prefix,json=networkPrefix,proto3" json:"network_prefix,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerIpRequest) Reset() {
	*x = GetContainerIpRequest{}
	mi := &file_worker_repo_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerIpRequest) ProtoMessage() {}

func (x *GetContainerIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerIpRequest.ProtoReflect.Descriptor instead.
func (*GetContainerIpRequest) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{26}
}

func (x *GetContainerIpRequest) GetNetworkPrefix() string {
	if x != nil {
		return x.NetworkPrefix
	}
	return ""
}

func (x *GetContainerIpRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type GetContainerIpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerIpResponse) Reset() {
	*x = GetContainerIpResponse{}
	mi := &file_worker_repo_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerIpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerIpResponse) ProtoMessage() {}

func (x *GetContainerIpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerIpResponse.ProtoReflect.Descriptor instead.
func (*GetContainerIpResponse) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{27}
}

func (x *GetContainerIpResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetContainerIpResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *GetContainerIpResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GetContainerIpsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkPrefix string                 `protobuf:"bytes,1,opt,name=network_prefix,json=networkPrefix,proto3" json:"network_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerIpsRequest) Reset() {
	*x = GetContainerIpsRequest{}
	mi := &file_worker_repo_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerIpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerIpsRequest) ProtoMessage() {}

func (x *GetContainerIpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerIpsRequest.ProtoReflect.Descriptor instead.
func (*GetContainerIpsRequest) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{28}
}

func (x *GetContainerIpsRequest) GetNetworkPrefix() string {
	if x != nil {
		return x.NetworkPrefix
	}
	return ""
}

type GetContainerIpsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Ips           []string               `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerIpsResponse) Reset() {
	*x = GetContainerIpsResponse{}
	mi := &file_worker_repo_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerIpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerIpsResponse) ProtoMessage() {}

func (x *GetContainerIpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerIpsResponse.ProtoReflect.Descriptor instead.
func (*GetContainerIpsResponse) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{29}
}

func (x *GetContainerIpsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetContainerIpsResponse) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *GetContainerIpsResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type RemoveContainerIpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkPrefix string                 `protobuf:"bytes,1,opt,name=network_prefix,json=networkPrefix,proto3" json:"network_prefix,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContainerIpRequest) Reset() {
	*x = RemoveContainerIpRequest{}
	mi := &file_worker_repo_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContainerIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContainerIpRequest) ProtoMessage() {}

func (x *RemoveContainerIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContainerIpRequest.ProtoReflect.Descriptor instead.
func (*RemoveContainerIpRequest) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{30}
}

func (x *RemoveContainerIpRequest) GetNetworkPrefix() string {
	if x != nil {
		return x.NetworkPrefix
	}
	return ""
}

func (x *RemoveContainerIpRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type RemoveContainerIpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContainerIpResponse) Reset() {
	*x = RemoveContainerIpResponse{}
	mi := &file_worker_repo_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContainerIpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContainerIpResponse) ProtoMessage() {}

func (x *RemoveContainerIpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_repo_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContainerIpResponse.ProtoReflect.Descriptor instead.
func (*RemoveContainerIpResponse) Descriptor() ([]byte, []int) {
	return file_worker_repo_proto_rawDescGZIP(), []int{31}
}

func (x *RemoveContainerIpResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RemoveContainerIpResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_worker_repo_proto protoreflect.FileDescriptor

const file_worker_repo_proto_rawDesc = "" +
	"\n" +
	"\x11worker_repo.proto\x1a\vtypes.proto\"=\n" +
	"\x1eGetNextContainerRequestRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\x94\x01\n" +
	"\x1fGetNextContainerRequestResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12D\n" +
	"\x11container_request\x18\x02 \x01(\v2\x17.types.ContainerRequestR\x10containerRequest\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\"Q\n" +
	"\x17SetImagePullLockRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\"]\n" +
	"\x18SetImagePullLockResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\"j\n" +
	"\x1aRemoveImagePullLockRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"J\n" +
	"\x1bRemoveImagePullLockResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"\x9d\x01\n" +
	"\x1bAddContainerToWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x1b\n" +
	"\tpool_name\x18\x03 \x01(\tR\bpoolName\x12!\n" +
	"\fpod_hostname\x18\x04 \x01(\tR\vpodHostname\"K\n" +
	"\x1cAddContainerToWorkerResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"\xa2\x01\n" +
	" RemoveContainerFromWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x1b\n" +
	"\tpool_name\x18\x03 \x01(\tR\bpoolName\x12!\n" +
	"\fpod_hostname\x18\x04 \x01(\tR\vpodHostname\"P\n" +
	"!RemoveContainerFromWorkerResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"3\n" +
	"\x14GetWorkerByIdRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"k\n" +
	"\x15GetWorkerByIdResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12%\n" +
	"\x06worker\x18\x02 \x01(\v2\r.types.WorkerR\x06worker\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\";\n" +
	"\x1cToggleWorkerAvailableRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"L\n" +
	"\x1dToggleWorkerAvailableResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"2\n" +
	"\x13RemoveWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"C\n" +
	"\x14RemoveWorkerResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"\xa9\x01\n" +
	"\x1bUpdateWorkerCapacityRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12'\n" +
	"\x0fcapacity_change\x18\x02 \x01(\x03R\x0ecapacityChange\x12D\n" +
	"\x11container_request\x18\x03 \x01(\v2\x17.types.ContainerRequestR\x10containerRequest\"K\n" +
	"\x1cUpdateWorkerCapacityResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"8\n" +
	"\x19SetWorkerKeepAliveRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"I\n" +
	"\x1aSetWorkerKeepAliveResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"j\n" +
	"\x15SetNetworkLockRequest\x12%\n" +
	"\x0enetwork_prefix\x18\x01 \x01(\tR\rnetworkPrefix\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\x05R\x03ttl\x12\x18\n" +
	"\aretries\x18\x03 \x01(\x05R\aretries\"[\n" +
	"\x16SetNetworkLockResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\"W\n" +
	"\x18RemoveNetworkLockRequest\x12%\n" +
	"\x0enetwork_prefix\x18\x01 \x01(\tR\rnetworkPrefix\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"H\n" +
	"\x19RemoveNetworkLockResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"\x80\x01\n" +
	"\x15SetContainerIpRequest\x12%\n" +
	"\x0enetwork_prefix\x18\x01 \x01(\tR\rnetworkPrefix\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\"E\n" +
	"\x16SetContainerIpResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"a\n" +
	"\x15GetContainerIpRequest\x12%\n" +
	"\x0enetwork_prefix\x18\x01 \x01(\tR\rnetworkPrefix\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\"d\n" +
	"\x16GetContainerIpResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\"?\n" +
	"\x16GetContainerIpsRequest\x12%\n" +
	"\x0enetwork_prefix\x18\x01 \x01(\tR\rnetworkPrefix\"X\n" +
	"\x17GetContainerIpsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03ips\x18\x02 \x03(\tR\x03ips\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\"d\n" +
	"\x18RemoveContainerIpRequest\x12%\n" +
	"\x0enetwork_prefix\x18\x01 \x01(\tR\rnetworkPrefix\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\"H\n" +
	"\x19RemoveContainerIpResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg2\x8d\n" +
	"\n" +
	"\x17WorkerRepositoryService\x12`\n" +
	"\x17GetNextContainerRequest\x12\x1f.GetNextContainerRequestRequest\x1a .GetNextContainerRequestResponse\"\x000\x01\x12I\n" +
	"\x10SetImagePullLock\x12\x18.SetImagePullLockRequest\x1a\x19.SetImagePullLockResponse\"\x00\x12R\n" +
	"\x13RemoveImagePullLock\x12\x1b.RemoveImagePullLockRequest\x1a\x1c.RemoveImagePullLockResponse\"\x00\x12U\n" +
	"\x14AddContainerToWorker\x12\x1c.AddContainerToWorkerRequest\x1a\x1d.AddContainerToWorkerResponse\"\x00\x12d\n" +
	"\x19RemoveContainerFromWorker\x12!.RemoveContainerFromWorkerRequest\x1a\".RemoveContainerFromWorkerResponse\"\x00\x12@\n" +
	"\rGetWorkerById\x12\x15.GetWorkerByIdRequest\x1a\x16.GetWorkerByIdResponse\"\x00\x12X\n" +
	"\x15ToggleWorkerAvailable\x12\x1d.ToggleWorkerAvailableRequest\x1a\x1e.ToggleWorkerAvailableResponse\"\x00\x12=\n" +
	"\fRemoveWorker\x12\x14.RemoveWorkerRequest\x1a\x15.RemoveWorkerResponse\"\x00\x12U\n" +
	"\x14UpdateWorkerCapacity\x12\x1c.UpdateWorkerCapacityRequest\x1a\x1d.UpdateWorkerCapacityResponse\"\x00\x12O\n" +
	"\x12SetWorkerKeepAlive\x12\x1a.SetWorkerKeepAliveRequest\x1a\x1b.SetWorkerKeepAliveResponse\"\x00\x12C\n" +
	"\x0eSetNetworkLock\x12\x16.SetNetworkLockRequest\x1a\x17.SetNetworkLockResponse\"\x00\x12L\n" +
	"\x11RemoveNetworkLock\x12\x19.RemoveNetworkLockRequest\x1a\x1a.RemoveNetworkLockResponse\"\x00\x12C\n" +
	"\x0eSetContainerIp\x12\x16.SetContainerIpRequest\x1a\x17.SetContainerIpResponse\"\x00\x12C\n" +
	"\x0eGetContainerIp\x12\x16.GetContainerIpRequest\x1a\x17.GetContainerIpResponse\"\x00\x12F\n" +
	"\x0fGetContainerIps\x12\x17.GetContainerIpsRequest\x1a\x18.GetContainerIpsResponse\"\x00\x12L\n" +
	"\x11RemoveContainerIp\x12\x19.RemoveContainerIpRequest\x1a\x1a.RemoveContainerIpResponse\"\x00B#Z!github.com/beam-cloud/beta9/protob\x06proto3"

var (
	file_worker_repo_proto_rawDescOnce sync.Once
	file_worker_repo_proto_rawDescData []byte
)

func file_worker_repo_proto_rawDescGZIP() []byte {
	file_worker_repo_proto_rawDescOnce.Do(func() {
		file_worker_repo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_repo_proto_rawDesc), len(file_worker_repo_proto_rawDesc)))
	})
	return file_worker_repo_proto_rawDescData
}

var file_worker_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_worker_repo_proto_goTypes = []any{
	(*GetNextContainerRequestRequest)(nil),    // 0: GetNextContainerRequestRequest
	(*GetNextContainerRequestResponse)(nil),   // 1: GetNextContainerRequestResponse
	(*SetImagePullLockRequest)(nil),           // 2: SetImagePullLockRequest
	(*SetImagePullLockResponse)(nil),          // 3: SetImagePullLockResponse
	(*RemoveImagePullLockRequest)(nil),        // 4: RemoveImagePullLockRequest
	(*RemoveImagePullLockResponse)(nil),       // 5: RemoveImagePullLockResponse
	(*AddContainerToWorkerRequest)(nil),       // 6: AddContainerToWorkerRequest
	(*AddContainerToWorkerResponse)(nil),      // 7: AddContainerToWorkerResponse
	(*RemoveContainerFromWorkerRequest)(nil),  // 8: RemoveContainerFromWorkerRequest
	(*RemoveContainerFromWorkerResponse)(nil), // 9: RemoveContainerFromWorkerResponse
	(*GetWorkerByIdRequest)(nil),              // 10: GetWorkerByIdRequest
	(*GetWorkerByIdResponse)(nil),             // 11: GetWorkerByIdResponse
	(*ToggleWorkerAvailableRequest)(nil),      // 12: ToggleWorkerAvailableRequest
	(*ToggleWorkerAvailableResponse)(nil),     // 13: ToggleWorkerAvailableResponse
	(*RemoveWorkerRequest)(nil),               // 14: RemoveWorkerRequest
	(*RemoveWorkerResponse)(nil),              // 15: RemoveWorkerResponse
	(*UpdateWorkerCapacityRequest)(nil),       // 16: UpdateWorkerCapacityRequest
	(*UpdateWorkerCapacityResponse)(nil),      // 17: UpdateWorkerCapacityResponse
	(*SetWorkerKeepAliveRequest)(nil),         // 18: SetWorkerKeepAliveRequest
	(*SetWorkerKeepAliveResponse)(nil),        // 19: SetWorkerKeepAliveResponse
	(*SetNetworkLockRequest)(nil),             // 20: SetNetworkLockRequest
	(*SetNetworkLockResponse)(nil),            // 21: SetNetworkLockResponse
	(*RemoveNetworkLockRequest)(nil),          // 22: RemoveNetworkLockRequest
	(*RemoveNetworkLockResponse)(nil),         // 23: RemoveNetworkLockResponse
	(*SetContainerIpRequest)(nil),             // 24: SetContainerIpRequest
	(*SetContainerIpResponse)(nil),            // 25: SetContainerIpResponse
	(*GetContainerIpRequest)(nil),             // 26: GetContainerIpRequest
	(*GetContainerIpResponse)(nil),            // 27: GetContainerIpResponse
	(*GetContainerIpsRequest)(nil),            // 28: GetContainerIpsRequest
	(*GetContainerIpsResponse)(nil),           // 29: GetContainerIpsResponse
	(*RemoveContainerIpRequest)(nil),          // 30: RemoveContainerIpRequest
	(*RemoveContainerIpResponse)(nil),         // 31: RemoveContainerIpResponse
	(*ContainerRequest)(nil),                  // 32: types.ContainerRequest
	(*Worker)(nil),                            // 33: types.Worker
}
var file_worker_repo_proto_depIdxs = []int32{
	32, // 0: GetNextContainerRequestResponse.container_request:type_name -> types.ContainerRequest
	33, // 1: GetWorkerByIdResponse.worker:type_name -> types.Worker
	32, // 2: UpdateWorkerCapacityRequest.container_request:type_name -> types.ContainerRequest
	0,  // 3: WorkerRepositoryService.GetNextContainerRequest:input_type -> GetNextContainerRequestRequest
	2,  // 4: WorkerRepositoryService.SetImagePullLock:input_type -> SetImagePullLockRequest
	4,  // 5: WorkerRepositoryService.RemoveImagePullLock:input_type -> RemoveImagePullLockRequest
	6,  // 6: WorkerRepositoryService.AddContainerToWorker:input_type -> AddContainerToWorkerRequest
	8,  // 7: WorkerRepositoryService.RemoveContainerFromWorker:input_type -> RemoveContainerFromWorkerRequest
	10, // 8: WorkerRepositoryService.GetWorkerById:input_type -> GetWorkerByIdRequest
	12, // 9: WorkerRepositoryService.ToggleWorkerAvailable:input_type -> ToggleWorkerAvailableRequest
	14, // 10: WorkerRepositoryService.RemoveWorker:input_type -> RemoveWorkerRequest
	16, // 11: WorkerRepositoryService.UpdateWorkerCapacity:input_type -> UpdateWorkerCapacityRequest
	18, // 12: WorkerRepositoryService.SetWorkerKeepAlive:input_type -> SetWorkerKeepAliveRequest
	20, // 13: WorkerRepositoryService.SetNetworkLock:input_type -> SetNetworkLockRequest
	22, // 14: WorkerRepositoryService.RemoveNetworkLock:input_type -> RemoveNetworkLockRequest
	24, // 15: WorkerRepositoryService.SetContainerIp:input_type -> SetContainerIpRequest
	26, // 16: WorkerRepositoryService.GetContainerIp:input_type -> GetContainerIpRequest
	28, // 17: WorkerRepositoryService.GetContainerIps:input_type -> GetContainerIpsRequest
	30, // 18: WorkerRepositoryService.RemoveContainerIp:input_type -> RemoveContainerIpRequest
	1,  // 19: WorkerRepositoryService.GetNextContainerRequest:output_type -> GetNextContainerRequestResponse
	3,  // 20: WorkerRepositoryService.SetImagePullLock:output_type -> SetImagePullLockResponse
	5,  // 21: WorkerRepositoryService.RemoveImagePullLock:output_type -> RemoveImagePullLockResponse
	7,  // 22: WorkerRepositoryService.AddContainerToWorker:output_type -> AddContainerToWorkerResponse
	9,  // 23: WorkerRepositoryService.RemoveContainerFromWorker:output_type -> RemoveContainerFromWorkerResponse
	11, // 24: WorkerRepositoryService.GetWorkerById:output_type -> GetWorkerByIdResponse
	13, // 25: WorkerRepositoryService.ToggleWorkerAvailable:output_type -> ToggleWorkerAvailableResponse
	15, // 26: WorkerRepositoryService.RemoveWorker:output_type -> RemoveWorkerResponse
	17, // 27: WorkerRepositoryService.UpdateWorkerCapacity:output_type -> UpdateWorkerCapacityResponse
	19, // 28: WorkerRepositoryService.SetWorkerKeepAlive:output_type -> SetWorkerKeepAliveResponse
	21, // 29: WorkerRepositoryService.SetNetworkLock:output_type -> SetNetworkLockResponse
	23, // 30: WorkerRepositoryService.RemoveNetworkLock:output_type -> RemoveNetworkLockResponse
	25, // 31: WorkerRepositoryService.SetContainerIp:output_type -> SetContainerIpResponse
	27, // 32: WorkerRepositoryService.GetContainerIp:output_type -> GetContainerIpResponse
	29, // 33: WorkerRepositoryService.GetContainerIps:output_type -> GetContainerIpsResponse
	31, // 34: WorkerRepositoryService.RemoveContainerIp:output_type -> RemoveContainerIpResponse
	19, // [19:35] is the sub-list for method output_type
	3,  // [3:19] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_worker_repo_proto_init() }
func file_worker_repo_proto_init() {
	if File_worker_repo_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_repo_proto_rawDesc), len(file_worker_repo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_repo_proto_goTypes,
		DependencyIndexes: file_worker_repo_proto_depIdxs,
		MessageInfos:      file_worker_repo_proto_msgTypes,
	}.Build()
	File_worker_repo_proto = out.File
	file_worker_repo_proto_goTypes = nil
	file_worker_repo_proto_depIdxs = nil
}
